### DISCUSSION TITLE
Actions as reusable building blocks?

### DISCUSSION THREAD

**Discussion by karolz-ms** [getporter/porter#1500] [Q&A]
Sorry if this is already covered somewhere--can actions be invoked from other actions?

Scenario: I have "login to Azure" action that consists of a few steps. I would like to perform these steps both as part of "install" action, as well as part of "uninstall" action. Is this possible?

**Comment by vdice** [comment]
To my knowledge, Porter doesn't currently have a concept or support for re-usable actions -- or steps (the building blocks that constitute a given action).  The same login step would need to be added to each action it is needed in.

@carolynvs may have suggestions on different approaches to accomplish the goal here w/o duplication.  Also, I thought there might've been an issue or two around this topic of action (or step) re-usability, but I'm failing to locate it.  We may need/want to create a new issue to capture this.

**Comment by carolynvs** [comment]
I have definitely both thought this myself and have fielded questions about it before but for the life of me, cannot find an existing issue. How about we think through what this would look like?

```yaml
login:
  - az:
      description: log into azure
      arguments:
        - login

install:
  - login
  - az:
      description: create a database and stuff
      ...
```

I'm not sure what would be more difficult but another syntax could be (below) so that it's easier to parse out.

```
install:
  - action: login
```

**Reply by karolz-ms** [reply]
That makes sense, thx Carolyn & Vaughn!

Another possibility would be to have a well-known action that has the semantics of "invoke this other action":

```yaml
login:
  - az:
      description: log into azure
      arguments:
        - login

install:
  - invoke:
      action: login
  - az:
      description: create a database and stuff
      ...
```

This might be slightly more future-proof in case you ever want to have some data other than just action ID/name associated with action invocation.

(update) just realized this is what you proposed as the alternative @carolynvs ... so I guess I like it ☺️
