### DISCUSSION TITLE
Streamlining reusing parameters on subsequent actions

### DISCUSSION THREAD

**Discussion by carolynvs** [getporter/porter#1672] [Ideas]
Porter has the ability to remember a parameter that you used previously and then use it in subsequent actions. For example, remembering the value of the "resource-group" parameter that you specified on install and using it automatically for upgrade, or persisting tfstate for the terraform mixin.

The problem is that it's not clear how to configure it. We could streamline the common scenarios for persisting state with a bundle and make those configurations more straightforward.

# I want to remember the value used for the parameter during install and reuse it later. 
In the example below, here's what's required to persist a parameter and reuse it later. You need an output declared, and then a parameter that sources the output:

```yaml
parameters:
- name: resource-group
  type: string
  path: /cnab/app/resource-group
  source:
    output: resource-group
  applyTo:
  - install
  - upgrade
  - uninstall

outputs:
- name: resource-group
  path: /cnab/app/resource-group
```

In the case where we just want to remember a parameter value from action to action, here is a potential shorthand:
```yaml
parameters:
- name: resource-group
  type: string
  persistent: true
```

The previous syntax would still be supported for advanced scenarios but for the most common just marking a parameter as persistent is a nice simplification. Under the hood we will expand that setting out to the bundle.json configuration used today.

When a parameter is sourced from an output, porter automatically appends "applyTo: <everything except install>" when applyTo isn't specified. That is why I specified applyTo in the example above, to make the parameter visible to the user for install, and require that it's specified.

# I want to generate a value during install and then reuse it later 

In this example, we are persisted the tfstate generated by the bundle during install and reusing it for subsequent steps:

```yaml
parameters:
  - name: tfstate
    type: file
    path: /cnab/app/terraform/terraform.tfstate
    source:
      output: tfstate

outputs:
  - name: tfstate
    type: file
    path: /cnab/app/terraform/terraform.tfstate
```

I suggest that we introduce a new section `state` to let the bundle author say that something needs to be kept track of, but not expose it to the user as something that they should be setting themselves.

```yaml
state:
  - name: tfstate
    path: /cnab/app/terraform/terraform.tfstate
```

So instead of having the user think about tfstate as a parameter or output when really they never pass it in, or will care about it as an output, we declare it as bundle state. Data that we want to have available to the bundle, but the user doesn't interact with.

What do you think? Does this line up with how you think about reusing values between bundle actions?
