### DISCUSSION TITLE
How to send ACI output to Azure storage File Share?

### DISCUSSION THREAD

**Discussion by hoangmnsd** [getporter/porter#1716] [Q&A]
Hello, I am new on using Porter. I have a question about Output:  

I passed these env variables to the ACI:
CNAB_AZURE_STATE_FILESHARE
CNAB_AZURE_STATE_STORAGE_ACCOUNT_NAME
CNAB_AZURE_STATE_STORAGE_ACCOUNT_KEY
CNAB_AZURE_STATE_PATH

use them in this ARM templates, I made some changes, but almost it's the same:
https://github.com/Azure/azure-cnab-quickstarts/blob/main/porter/aks/azuredeploy-simple.json

in porter.yaml I have configured outputs already:  
```yaml
outputs:
- name: kubeconfig
  type: string
  description: "Kubeconfig for the AKS cluster"
  sensitive: true
  applyTo:
    - "install"
    
    
install:
  - az: 
      description: "Azure CLI AKS get-credentials"
      arguments: 
        - "aks" 
        - "get-credentials" 
      flags:
        resource-group: "{{ bundle.parameters.resource_group }}"
        name: "{{ bundle.parameters.cluster_name }}"
        file: "/root/.kube/config"
      outputs:
        - name: kubeconfig
          path: /root/.kube/config

```
ACI run successful, but the output is not exist in Azure Storage File share.  
Did I made wrong configuration?  Anyone did this successful recently? 
How can I debug to ensure that the `ouput` block is working fine?

I've read this README file of this repo but it doesn't help: 
https://github.com/deislabs/cnab-azure-driver
