### DISCUSSION TITLE
Should interactive commands be possible with the docker-compose mixin?

### DISCUSSION THREAD

**Discussion by martinburchell** [getporter/porter#1816] [Q&A] [answered]
I'm trying to create a custom action to run a script that essentially calls the interactive Django command `manage.py createsuperuser ` using the docker-compose mixin:

If I run:
`docker-compose run --rm crate_workers /bin/bash -c "source /crate/venv/bin/activate; crate_django_manage createsuperuser"`
it works fine:

```
Username (leave blank to use 'root'): admin
Email address: admin@example.com
Password:
Password (again):
Superuser created successfully.
```

However, with this entry in my porter.yaml:

```
django-manage-createsuperuser:
  - docker-compose:
      description: "Create a database superuser"
      arguments:
        - run
        - --rm crate_workers
        - /bin/bash -c "source /crate/venv/bin/activate; crate_django_manage createsuperuser"
```

When I run:

`porter invoke --action django-manage-createsuperuser --parameter-set crateanon --cred crateanon --allow-docker-host-access`

I get this message:
```
Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.
```

Is Porter doing something to disable the TTY?

EDIT

Minimal example:

https://github.com/martinburchell/porter-test/blob/main/porter.yaml
https://github.com/martinburchell/porter-test/blob/main/docker-compose.yaml
```

porter invoke --action tty-test --allow-docker-host-access
Building bundle ===>
Copying porter runtime ===>
Copying mixins ===>
Copying mixin docker ===>
Copying mixin docker-compose ===>
Copying mixin exec ===>

Generating Dockerfile =======>

Writing Dockerfile =======>

Starting Invocation Image Build (crateanon/porter-test-installer:v0.1.0) =======>
invoking porter-test...
executing tty-test action from porter-test (installation: porter-test)
Test if there is a tty
Creating app_porter_test_run ...
Creating app_porter_test_run ... done
no tty
execution completed successfully!
```

```
[11:02:03 porter-test]$ docker-compose run --rm porter_test /bin/bash -c "if [ -t 0 ]; then echo tty; else echo no tty; fi"
Creating porter-test_porter_test_run ... done
tty
```
