### DISCUSSION TITLE
How to specify image tag/digest at build time

### DISCUSSION THREAD

**Discussion by madrum** [getporter/porter#1882] [Q&A] [answered]
I have a pipeline building and publishing an image of my application, e.g. myapp:1.0.2.
After that step, I want to publish a Porter bundle with that version of the application, plus scripts and charts needed for the deployment, for an air-gapped environment.

The porter.yaml file will need the tag/digest value updated to allow the image to be added to the porter bundle when porter build/publish is ran. I do not see how to accomplish this with the porter CLI as you cannot pass parameters into the porter build/publish commands.

Does the Porter CLI allow for setting the image tag/digest when running `porter build` or `porter publish`? Or, is it expected to  manually edit the porter.yaml file, like with a `sed` command?

Thanks, Mike

**Comment by carolynvs** [comment, marked as answer]
We are working on adding build argument support for the v1 release (in #1789, #1769 and #1124). Until that's implemented, you will need to use tools like sed to edit the porter.yaml as a stopgap measure.

Once it is in place you should be able to use this:

`porter build --custom myimageDigest sha256:abc123`

```yaml
name: mybundle

custom:
  myimageDigest: "sha256:85b1a9b4b60a4cf73a23517dad677e64edf467107fa7d58fce9c50e6a3e4c914" # default digest to use

images:
  myimage:
      description: "A simple web service"
      imageType: "docker"
      repository: "jeremyrickard/devops-days-msp"
      digest: "{{bundle.custom.myimageDigest}}"
```
