### DISCUSSION TITLE
Explanations about architecture of complex mixins.

### DISCUSSION THREAD

**Discussion by LvffY** [getporter/porter#1934] [Q&A]
Hello

I'm trying to build an [ansible mixin](https://github.com/LvffY/ansible-mixin) and like the [docker mixin](https://github.com/getporter/docker-mixin) I'd like to have some custom structure.

For example, the following steps would be correct : 

```yaml
install:
  - ansible:
      description: "Run our ansible playbookcommand"
      playbook: 
        arguments:
          - "playbook.yml"
        flags:
          inventory: "hosts"
  - ansible:
      description: "Run our ansible galaxy command"
      galaxy: 
        arguments:
          - "collection"
          - "install"
          - "community.general"
   - ansible:
      description: "Run our ansible ahdoc command"
      adhoc: 
        arguments:
          - "localhost"
        flags:
          module-name: "debug"
          args: "msg='Hello from ansible AdHoc command !'"
```

While I read about the [**action.go** of docker-mixin](https://github.com/getporter/docker-mixin/blob/main/pkg/docker/action.go) I'm really new to golang and I don't understant how to adapt the docker mixin code to make my ansible mixin.

It would be great to have some kind of documentation about this kind of mixin architecture for noobs like me :)

Thanks for your help !

LvffY
