### DISCUSSION TITLE
kind + porter + kubeconfig: connect: connection refused

### DISCUSSION THREAD

**Discussion by snocke** [getporter/porter#2215] [Q&A] [answered]
Hi there,
I'm using an M1 and I'm trying to use porter with my KinD Cluster. I've followed the https://porter.sh/best-practices/kind/ instructions. However, porter is always trying to connect to the default IP and not the actual ~/.kube/config
`kubectl cluster-info`                             
`Kubernetes control plane is running at https://10.15.19.162:6443`
`CoreDNS is running at https://10.15.19.162:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy`

Executing `porter install -c kubeconfig` results in:
`unable to recognize "kubernetes/manifests/hbase.yml": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused`

I've also tried the new kubeConfig (https://github.com/getporter/kubernetes-mixin/blob/main/pkg/kubernetes/testdata/install-input-with-kubeconfig.yaml). However, I receive the error `error: stat /Users/me/.kube/config: no such file or directory` when executing `porter install -c kubeconfig`

I wonder about the origin of the problem. Is it due to the M1? Is it Porter? Or did I configure something wrong?
Anyone running in similar problems or got an idea for a fix?
I appreciate any help. Thanks!

**Comment by carolynvs** [comment, marked as answer]
Have you tried the steps from our guide to using KinD with Porter yet? https://getporter.org/best-practices/kind/

**Reply by snocke** [reply]
thanks. Yes, i tried that. Specified a `kind-config.yaml `with the ip adress extracted from `ifconfig en0 | awk '/inet / {print $2; }' | cut -d ' ' -f 2`. I'm gonna produce some logs for more insights and post it here.

**Reply by carolynvs** [reply]
This error message is usually what you see when there isn't a kubeconfig in the location where kubectl expects it, so it's attempting the default address. 

```
unable to recognize "kubernetes/manifests/hbase.yml": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
```

Here's what your porter.yaml should look like (below). Also make sure that you are using v0.28.5 of the kubernetes mixin:

```yaml
mixins:
  - kubernetes

credentials:
  - name: kubeconfig
    # Note we changed from /home/root to /home/nonroot in a recent version of v1
    path: /home/nonroot/.kube/config

install:
  - exec:
      description: "Check connectivity"
      command: kubectl
      arguments:
        - get
        - nodes
```
