### DISCUSSION TITLE
Chaining outputs without defining them at the bundle level

### DISCUSSION THREAD

**Discussion by tamirkamara** [getporter/porter#2230] [Q&A] [answered]
Hi,

Is there a way to use one step's outputs in a following one without defining those as bundle level outputs?

Something similar to this:
```yaml
myaction:
  - terraform:
      description: "1 get some outputs"
      arguments:
        - "output"      
      vars:
        ...
      backendConfig:
        ...
      outputs:
        - name: some_var
  - exec:
      description: "2 use outputs"
      command: ./1.sh
      arguments:
        - "{{ bundle.actions.myaction[0].outputs.some_var }}"
```
