### DISCUSSION TITLE
Dependencies and Credentials

### DISCUSSION THREAD

**Discussion by tamirkamara** [getporter/porter#2310] [Q&A]
Hi,

In a situation where a parent bundle depends on a child bundle and both have credentials (same ones), how should those be passed along?
There's a parameters object under a dependency but nothing is mentioned about credentials...

**Comment by carolynvs** [comment]
All credentials supplied to the parent bundle are passed along to any dependencies in the current implementation of dependencies. This means that if you are using a dependency that needs a credential, you must redeclare that credential on the parent bundle too.

This is something that is being completely overhauled in the proposal for changing dependencies in Porter but is a long way off from being implemented.

**Comment by tamirkamara** [comment]
Hi @carolynvs,
I might had mis-diagnose the issue I was seeing - trying to do something like this:
```
dependencies:
  - name: child
    reference: myacr/child:v0.1.0
    parameters:
      tre_id: "{{ bundle.parameters.tre_id }}"
      id: "{{ bundle.parameters.id }}"
      azure_location: "{{ bundle.parameters.azure_location }}"
      tfstate_resource_group_name: "{{ bundle.parameters.tfstate_resource_group_name }}"
      tfstate_storage_account_name: "{{ bundle.parameters.tfstate_storage_account_name }}"
      tfstate_container_name: "{{ bundle.parameters.tfstate_container_name }}"
```
Essentially chaining the parent's parameters and passing them to the child call.
Isn't it possible in v0?
