### DISCUSSION TITLE
Optional Environment Parameters

### DISCUSSION THREAD

**Discussion by tamirkamara** [getporter/porter#2467] [Q&A] [answered]
We're upgrading to v1 and saw that using parameters file directly in actions (like install) is deprecated so we also move to a set too.
Thing is that it doesn't behave the same way, perhaps it's because of the set but might also be a change in v1. Using the following set will fail if PARAM1 environment variable isn't set...
We do this a lot mainly for optional bundle parameters.
Do you have any advice?

```yaml
schemaType: ParameterSet
schemaVersion: 1.0.1
namespace: ""
name: bundle1
parameters:
  - name: param1
    source:
      env: PARAM1
```

```
rpc error: code = Unknown desc = environment variable env is not defined
unable to process provided parameter sets: 1 error occurred:
        * unable to resolve parameter bundle1.param1 from env PARAM1: rpc error: code = Unknown desc = environment variable env is not defined
```
