### ISSUE TITLE
Lint for parameters being used in actions to which they don't apply

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1018]
After #1017, it will be a hard runtime failure if your porter.yaml attempts to use `{{bundle.paramters.PARAM}}` when `PARAM` was defined to not apply to the action where that templated value is used.

We should lint for this and hard fail so that we can detect and correct this problem at build time.

Example:

```yaml
parameters:
- name: connstr
   type: string
   applyTo:
    - install

uninstall:
  - exec:
      description: "Use a non-applicable parameter"
      command: ./helpers.sh
      arguments:
      - "{{ bundle.parameters.connstr }}"
```

This should be an porter level linter, not a mixin specific linter, which would be our first.
