### ISSUE TITLE
Add the instance name to the avilable template variables

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1035]
It would be useful when I'm installing a bundle if I could access the instance name of the bundle, not just the published name of the bundle. For example, I could use it to default the release name of my helm releases to something more unique.

Here is what I would like to do, note that this relies on being able to use templates throughout the bundle, not just in the action.

```yaml
parameters:
  - name: release
    description: helm release name
    type: string
    default: "{{ installation.name }}"
```

I am also assuming that we have already changed the term `instance` to `installation` at this point. I'd like to be consistent with whatever we decide to do with that.
