### ISSUE TITLE
Error on publish to Harbor 2.0 (OCI-compliant) registry

### ISSUE THREAD

**Issue by digger18** [getporter/porter#1229]
## Describe the bug
Harbor 2.0 should be fully OCI-compliant (https://goharbor.io/blog/harbor-2.0/) registry, but Porter fails to publish CNAB bundles to it.
In the Harbor UI, there are specific instructions on how to push CNAB packages using `cnab-to-oci` which makes even a stronger case why Porter should be able to publish to it.
The push command is: `cnab-to-oci push CNAB_PATH --target 172.31.33.xxx/library/REPOSITORY[:TAG] --auto-update-bundle`

## Expected behavior
CNAB bundle is successfully pushed to Harbor and available for deployment.

## Porter Command and Output
```
# porter publish --debug
DEBUG name:    arm
DEBUG pkgDir: /root/.porter/mixins/arm
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/arm/arm version --output json --debug
DEBUG name:    aws
DEBUG pkgDir: /root/.porter/mixins/aws
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/aws/aws version --output json --debug
DEBUG name:    az
DEBUG pkgDir: /root/.porter/mixins/az
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/az/az version --output json --debug
DEBUG name:    exec
DEBUG pkgDir: /root/.porter/mixins/exec
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/exec/exec version --output json --debug
DEBUG name:    gcloud
DEBUG pkgDir: /root/.porter/mixins/gcloud
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/gcloud/gcloud version --output json --debug
DEBUG name:    helm
DEBUG pkgDir: /root/.porter/mixins/helm
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/helm/helm version --output json --debug
DEBUG name:    kubernetes
DEBUG pkgDir: /root/.porter/mixins/kubernetes
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/kubernetes/kubernetes version --output json --debug
DEBUG name:    terraform
DEBUG pkgDir: /root/.porter/mixins/terraform
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/terraform/terraform version --output json --debug
Pushing CNAB invocation image...
The push refers to repository [172.31.33.xxx/library/infra-cnab-installer]
08d3279ecc54: Preparing
b92dc245d8c2: Preparing
8363e3460c66: Preparing
4eb4a6386afd: Preparing
219410cd4347: Preparing
90ca8ca0957c: Preparing
8e7363b9dcd4: Preparing
9b7657a76455: Preparing
4e38024e7e09: Preparing
90ca8ca0957c: Waiting
8e7363b9dcd4: Waiting
9b7657a76455: Waiting
4e38024e7e09: Waiting
219410cd4347: Mounted from library/infra-install-cnab-installer
8363e3460c66: Pushed
08d3279ecc54: Pushed
90ca8ca0957c: Mounted from library/infra-install-cnab-installer
8e7363b9dcd4: Mounted from library/infra-install-cnab-installer
9b7657a76455: Mounted from library/infra-install-cnab-installer
4e38024e7e09: Mounted from library/infra-install-cnab-installer
4eb4a6386afd: Pushed
b92dc245d8c2: Pushed
0.0.1: digest: sha256:b1f065f32e9ca151fc47d6905c901ffb306ca7d01b92a096c130cb0d51989dca size: 2214

Rewriting CNAB bundle.json...
DEBUG name:    arm
DEBUG pkgDir: /root/.porter/mixins/arm
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/arm/arm version --output json --debug
DEBUG name:    aws
DEBUG pkgDir: /root/.porter/mixins/aws
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/aws/aws version --output json --debug
DEBUG name:    az
DEBUG pkgDir: /root/.porter/mixins/az
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/az/az version --output json --debug
DEBUG name:    exec
DEBUG pkgDir: /root/.porter/mixins/exec
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/exec/exec version --output json --debug
DEBUG name:    gcloud
DEBUG pkgDir: /root/.porter/mixins/gcloud
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/gcloud/gcloud version --output json --debug
DEBUG name:    helm
DEBUG pkgDir: /root/.porter/mixins/helm
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/helm/helm version --output json --debug
DEBUG name:    kubernetes
DEBUG pkgDir: /root/.porter/mixins/kubernetes
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/kubernetes/kubernetes version --output json --debug
DEBUG name:    terraform
DEBUG pkgDir: /root/.porter/mixins/terraform
DEBUG file:     
DEBUG stdin:

/root/.porter/mixins/terraform/terraform version --output json --debug
Starting to copy image 172.31.33.xxx/library/infra-cnab-installer:0.0.1...
Failed to copy image 172.31.33.xxx/library/infra-cnab-installer:0.0.1: failed to resolve or push image for service "InvocationImage"
Error: failed to resolve or push image for service "InvocationImage"
```

## Version
porter v0.27.2 (aee93e98)

**Comment by vdice** [comment]
To double-check, does `cnab-to-oci push CNAB_PATH --target 172.31.33.xxx/library/REPOSITORY[:TAG] --auto-update-bundle` work when the bundle.json generated by Porter is supplied?  (It should exist at `.cnab/bundle.json` in the working directory of the Porter bundle, after `porter build` is run.)

**Comment by digger18** [comment]
> To double-check, does `cnab-to-oci push CNAB_PATH --target 172.31.33.xxx/library/REPOSITORY[:TAG] --auto-update-bundle` work when the bundle.json generated by Porter is supplied? (It should exist at `.cnab/bundle.json` in the working directory of the Porter bundle, after `porter build` is run.)

Just tested, it does not work either.
Exact same error.

**Comment by vdice** [comment]
@digger18 thank you for testing.  As the errors are the same, I'm tempted to file this under the https://github.com/cnabio/cnab-to-oci repo as a result.  Perhaps some maintainers of that repo might have some ideas. 
 Porter is currently on the most recent release of cnab-to-oci, but we can bump when the issue(s) and fix(es) make it into cnab-to-oci.

**Comment by vdice** [comment]
Oh wait, I did notice the invocation image name is: `172.31.33.xxx/library/infra-cnab-installer:0.0.1`.  It wouldn't be an official library image, right?  I wonder if the cause of failure is ?  Can the bundle `tag` value in the Porter manifest be provided?  I wonder if somehow `library` is mistakenly replacing an org/domain value you've supplied.

**Comment by radu-matei** [comment]
Thanks for reporting this, @digger18.
Could you please try using [this minimal bundle from the `cnab-to-oci` repo](https://github.com/cnabio/cnab-to-oci/blob/master/examples/helloworld-cnab/bundle.json)?

(I don't have access to a Harbor instance right now, but I will try to reproduce it as well.)

**Comment by digger18** [comment]
> Oh wait, I did notice the invocation image name is: `172.31.33.xxx/library/infra-cnab-installer:0.0.1`. It wouldn't be an official library image, right? I wonder if this is the cause of failure. Can the bundle `tag` value in the Porter manifest be provided? I wonder if somehow `library` is mistakenly replacing an org/domain value you've supplied.

I tried to change `library` to `cnab` and it fails with the same error.
```
root@ip-172-31-33-128:~/infra-helm-charts-porter# porter build
Copying porter runtime ===> 
Copying mixins ===> 
Copying mixin exec ===> 
Copying mixin helm ===> 

Generating Dockerfile =======>

Writing Dockerfile =======>

Starting Invocation Image Build =======> 
root@ip-172-31-33-128:~/infra-helm-charts-porter# porter publish
Pushing CNAB invocation image...
The push refers to repository [172.31.33.128/cnab/infra-cnab-installer]
1ca7e1e82fed: Preparing
575cec06104a: Preparing
6c880c27fe2d: Preparing
fa6795c53ced: Preparing
219410cd4347: Preparing
90ca8ca0957c: Preparing
8e7363b9dcd4: Preparing
9b7657a76455: Preparing
4e38024e7e09: Preparing
8e7363b9dcd4: Waiting
9b7657a76455: Waiting
4e38024e7e09: Waiting
90ca8ca0957c: Waiting
219410cd4347: Mounted from library/infra-cnab-installer-installer
6c880c27fe2d: Pushed
1ca7e1e82fed: Pushed
90ca8ca0957c: Mounted from library/infra-cnab-installer-installer
8e7363b9dcd4: Mounted from library/infra-cnab-installer-installer
9b7657a76455: Mounted from library/infra-cnab-installer-installer
4e38024e7e09: Mounted from library/infra-cnab-installer-installer
575cec06104a: Pushed
fa6795c53ced: Pushed
1.0: digest: sha256:82c159abc5969ebb23220c0527fe43dbff735ba58aac8a5fc0f2ad230b6c6794 size: 2214

Rewriting CNAB bundle.json...
Starting to copy image 172.31.33.128/cnab/infra-cnab-installer:1.0...
Failed to copy image 172.31.33.128/cnab/infra-cnab-installer:1.0: failed to resolve or push image for service "InvocationImage"
Error: failed to resolve or push image for service "InvocationImage"
```


My porter.yaml:
```
root@ip-172-31-33-128:~/infra-helm-charts-porter# cat porter.yaml 
# This is the configuration for Porter
# You must define steps for each action, but the rest is optional
# See https://porter.sh/author-bundles for documentation on how to configure your bundle
# Uncomment out the sections below to take full advantage of what Porter can do!

name: infra-cnab
version: 0.0.1
description: "Infra CNAB"
tag: 172.31.33.128/cnab/infra-cnab:1.0

# Uncomment the line below to use a template Dockerfile for your invocation image
#dockerfile: Dockerfile.tmpl

mixins:
- exec
- helm

parameters:
- name: LOCAL_PATH_PROVISIONER
  description: "Install/Upgrade Local Path Provisioner"
  type: string
  default: "true"
  env: LOCAL_PATH_PROVISIONER

- name: CERT_MANAGER
  description: "Install/Upgrade Cert-Manager"
  type: string
  default: "true"
  env: CERT_MANAGER

- name: NGINX_INGRESS
  description: "Install/Upgrade Nginx Ingress"
  type: string
  default: "true"
  env: NGINX_INGRESS

- name: ARGO
  description: "Install/Upgrade Argo"
  type: string
  default: "false"
  env: ARGO

- name: CHARTMUSEUM
  description: "Install/Upgrade ChartMuseum"
  type: string
  default: "true"
  env: CHARTMUSEUM

- name: NGINX_LOCAL_REPO
  description: "Install/Upgrade Nginx Local Repository"
  type: string
  default: "true"
  env: NGINX_LOCAL_REPO

- name: RANCHER
  description: "Install/Upgrade Rancher"
  type: string
  default: "true"
  env: RANCHER

- name: PROMETHEUS_STACK
  description: "Install/Upgrade Prometheus Stack"
  type: string
  #default: "true"
  default: "false"
  env: PROMETHEUS_STACK

- name: METALLB
  description: "Install/Upgrade MetalLB"
  type: string
  default: "false"
  env: METALLB

#- name: IP_ADDRESSES
#  description: "IP address range allocated for MetalLB, e.g. {192.168.20.12-192.168.20.15} or {192.168.20.32/32,192.168.20.47/32}"
#  type: string
#  default: "" # example: {192.168.20.12-192.168.20.15} or {192.168.20.32/32,192.168.20.47/32}
#  env: IP_ADDRESSES

  
images:
  metallb-speaker:
    repository: "docker.io/metallb/speaker"
    tag: "v0.9.3"

  metallb-controller:
    repository: "docker.io/metallb/controller"
    tag: "v0.9.3"

  nvidia-dcgm-exporter:
    repository: "nvidia/dcgm-exporter"
    tag: "1.4.6"

  nginx-ingress-controller:
    repository: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller"
    tag: "0.32.0"

#  prometheus:
#    repository: "quay.io/prometheus/prometheus"
#    tag: "v2.17.2"
#
#  prometheus-node-exporter:
#    repository: "quay.io/prometheus/node-exporter"
#    tag: "v0.18.0"
#
#  prometheus-config-reloader:
#    repository: "quay.io/coreos/prometheus-config-reloader"
#    tag: "v0.31.1"
#
#  prometheus-configmap-reload:
#    repository: "quay.io/coreos/configmap-reload"
#    tag: "v0.0.1"
#
#  prometheus-pushgateway:
#    repository: "prom/pushgateway"
#    tag: "v0.9.1"
#
#  prometheus-operator:
#    repository: "quay.io/coreos/prometheus-operator"
#    tag: "v0.31.1"
#
#  kube-state-metrics:
#    repository: "quay.io/coreos/kube-state-metrics"
#    tag: "v1.7.2"
#
#  rancher-agent:
#    repository: "rancher/rancher-agent"
#    tag: "v2.3.5"
#
  rancher:
    repository: "rancher/rancher"
    tag: "v2.3.5"

  busybox:
    repository: "busybox"
    tag: "latest"

  cert-manager-cainjector:
    repository: "quay.io/jetstack/cert-manager-cainjector"
    tag: "v0.12.0"

  cert-manager-controller:
    repository: "quay.io/jetstack/cert-manager-controller"
    tag: "v0.12.0"

  cert-manager-webhook:
    repository: "quay.io/jetstack/cert-manager-webhook"
    tag: "v0.12.0"

  kube-webhook-certgen:
    repository: "jettech/kube-webhook-certgen"
    tag: "v1.0.0"

  chartmuseum:
    repository: "chartmuseum/chartmuseum"
    tag: "v0.11.0"

  local-path-provisioner:
    repository: "rancher/local-path-provisioner"
    tag: "v0.0.12"

  defaultbackend-amd64:
    repository: "k8s.gcr.io/defaultbackend-amd64"
    tag: "1.5"

  nginx:
    repository: "nginx"
    tag: "1.17.3-alpine"

  grafana-plugins:
    repository: "gcr.io/rec-repo/grafana-plugins"
    tag: "master"

  kiwigrid-k8s-sidecar:
    repository: "kiwigrid/k8s-sidecar"
    tag: "0.1.20"

  grafana:
    repository: "grafana/grafana"
    tag: "6.3.5"

  squareup-ghostunnel:
    repository: "squareup/ghostunnel"
    tag: "v1.4.1"

  debian-tall:
    repository: "quay.io/gravitational/debian-tall"
    tag: "stretch"

  container-tools:
    repository: "gcr.io/rec-repo/container-tools"
    tag: "1.0.7"


install:
  - exec:
      description: "Install Infra Charts"
      command: ./install.sh

#upgrade:
#  - exec:
#      description: "World 2.0"
#      command: ./helpers.sh
#      arguments:
#        - upgrade

uninstall:
  - exec:
      description: "Uninstall Infra Charts"
      command: ./uninstall.sh

# See https://porter.sh/wiring/#credentials
#credentials:
#  - name: kubeconfig
#    path: /root/.kube/config
```

**Comment by digger18** [comment]
> Thanks for reporting this, @digger18.
> Could you please try using [this minimal bundle from the `cnab-to-oci` repo](https://github.com/cnabio/cnab-to-oci/blob/master/examples/helloworld-cnab/bundle.json)?
> 
> (I don't have access to a Harbor instance right now, but I will try to reproduce it as well.)

It works with the minimal bundle:
```
# cnab-to-oci push bundle.json --insecure-registries 172.31.33.128:80 --target 172.31.33.128:80/library/helloworld:0.1.1 --auto-update-bundle
Starting to copy image cnab/helloworld:0.1.1...
Completed image cnab/helloworld:0.1.1 copy
Pushed successfully, with digest "sha256:55c6da48fe8553696bf3e2c940ea667e2d2fda3d55614a19dbd7d084780c0807"
```

It led me to the understanding that I require `--insecure-registry` in my `porter publish` command, but it still does not work with my bundle:
```
# porter publish --insecure-registry
Pushing CNAB invocation image...
The push refers to repository [172.31.33.128:80/library/infra-cnab-installer]
78260943389b: Preparing
06e97b022485: Preparing
8c42c6e74806: Preparing
1ee8b2c50107: Preparing
219410cd4347: Preparing
90ca8ca0957c: Preparing
8e7363b9dcd4: Preparing
9b7657a76455: Preparing
4e38024e7e09: Preparing
8e7363b9dcd4: Waiting
9b7657a76455: Waiting
4e38024e7e09: Waiting
90ca8ca0957c: Waiting
219410cd4347: Layer already exists
90ca8ca0957c: Layer already exists
8c42c6e74806: Pushed
8e7363b9dcd4: Layer already exists
9b7657a76455: Layer already exists
78260943389b: Pushed
4e38024e7e09: Layer already exists
06e97b022485: Pushed
1ee8b2c50107: Pushed
1.0.0: digest: sha256:f95c7056860e1f9ac90b7c9668cd7447a1d1d1260c6e81f6844ab50b63947874 size: 2214

Rewriting CNAB bundle.json...
Starting to copy image 172.31.33.128:80/library/infra-cnab-installer:1.0.0...
Failed to copy image 172.31.33.128:80/library/infra-cnab-installer:1.0.0: failed to resolve or push image for service "InvocationImage"
Error: failed to resolve or push image for service "InvocationImage"
```

My slightly revised porter.yaml:
```
# cat porter.yaml 
# This is the configuration for Porter
# You must define steps for each action, but the rest is optional
# See https://porter.sh/author-bundles for documentation on how to configure your bundle
# Uncomment out the sections below to take full advantage of what Porter can do!

name: infra-cnab
version: 1.0.0
description: "Infra CNAB"
tag: 172.31.33.128:80/library/infra-cnab:1.0.0

# Uncomment the line below to use a template Dockerfile for your invocation image
#dockerfile: Dockerfile.tmpl

mixins:
- exec
- helm

parameters:
- name: LOCAL_PATH_PROVISIONER
  description: "Install/Upgrade Local Path Provisioner"
  type: string
  default: "true"
  env: LOCAL_PATH_PROVISIONER

- name: CERT_MANAGER
  description: "Install/Upgrade Cert-Manager"
  type: string
  default: "true"
  env: CERT_MANAGER

- name: NGINX_INGRESS
  description: "Install/Upgrade Nginx Ingress"
  type: string
  default: "true"
  env: NGINX_INGRESS

- name: ARGO
  description: "Install/Upgrade Argo"
  type: string
  default: "false"
  env: ARGO

- name: CHARTMUSEUM
  description: "Install/Upgrade ChartMuseum"
  type: string
  default: "true"
  env: CHARTMUSEUM

- name: NGINX_LOCAL_REPO
  description: "Install/Upgrade Nginx Local Repository"
  type: string
  default: "true"
  env: NGINX_LOCAL_REPO

- name: RANCHER
  description: "Install/Upgrade Rancher"
  type: string
  default: "true"
  env: RANCHER

- name: PROMETHEUS_STACK
  description: "Install/Upgrade Prometheus Stack"
  type: string
  #default: "true"
  default: "false"
  env: PROMETHEUS_STACK

- name: METALLB
  description: "Install/Upgrade MetalLB"
  type: string
  default: "false"
  env: METALLB

#- name: IP_ADDRESSES
#  description: "IP address range allocated for MetalLB, e.g. {192.168.20.12-192.168.20.15} or {192.168.20.32/32,192.168.20.47/32}"
#  type: string
#  default: "" # example: {192.168.20.12-192.168.20.15} or {192.168.20.32/32,192.168.20.47/32}
#  env: IP_ADDRESSES

  
images:
  metallb-speaker:
    repository: "docker.io/metallb/speaker"
    tag: "v0.9.3"

  metallb-controller:
    repository: "docker.io/metallb/controller"
    tag: "v0.9.3"

  nvidia-dcgm-exporter:
    repository: "nvidia/dcgm-exporter"
    tag: "1.4.6"

  nginx-ingress-controller:
    repository: "quay.io/kubernetes-ingress-controller/nginx-ingress-controller"
    tag: "0.32.0"

#  prometheus:
#    repository: "quay.io/prometheus/prometheus"
#    tag: "v2.17.2"
#
#  prometheus-node-exporter:
#    repository: "quay.io/prometheus/node-exporter"
#    tag: "v0.18.0"
#
#  prometheus-config-reloader:
#    repository: "quay.io/coreos/prometheus-config-reloader"
#    tag: "v0.31.1"
#
#  prometheus-configmap-reload:
#    repository: "quay.io/coreos/configmap-reload"
#    tag: "v0.0.1"
#
#  prometheus-pushgateway:
#    repository: "prom/pushgateway"
#    tag: "v0.9.1"
#
#  prometheus-operator:
#    repository: "quay.io/coreos/prometheus-operator"
#    tag: "v0.31.1"
#
#  kube-state-metrics:
#    repository: "quay.io/coreos/kube-state-metrics"
#    tag: "v1.7.2"
#
#  rancher-agent:
#    repository: "rancher/rancher-agent"
#    tag: "v2.3.5"
#
  rancher:
    repository: "rancher/rancher"
    tag: "v2.3.5"

  busybox:
    repository: "busybox"
    tag: "latest"

  cert-manager-cainjector:
    repository: "quay.io/jetstack/cert-manager-cainjector"
    tag: "v0.12.0"

  cert-manager-controller:
    repository: "quay.io/jetstack/cert-manager-controller"
    tag: "v0.12.0"

  cert-manager-webhook:
    repository: "quay.io/jetstack/cert-manager-webhook"
    tag: "v0.12.0"

  kube-webhook-certgen:
    repository: "jettech/kube-webhook-certgen"
    tag: "v1.0.0"

  chartmuseum:
    repository: "chartmuseum/chartmuseum"
    tag: "v0.11.0"

  local-path-provisioner:
    repository: "rancher/local-path-provisioner"
    tag: "v0.0.12"

  defaultbackend-amd64:
    repository: "k8s.gcr.io/defaultbackend-amd64"
    tag: "1.5"

  nginx:
    repository: "nginx"
    tag: "1.17.3-alpine"

  grafana-plugins:
    repository: "gcr.io/rec-repo/grafana-plugins"
    tag: "master"

  kiwigrid-k8s-sidecar:
    repository: "kiwigrid/k8s-sidecar"
    tag: "0.1.20"

  grafana:
    repository: "grafana/grafana"
    tag: "6.3.5"

  squareup-ghostunnel:
    repository: "squareup/ghostunnel"
    tag: "v1.4.1"

  debian-tall:
    repository: "quay.io/gravitational/debian-tall"
    tag: "stretch"

  container-tools:
    repository: "gcr.io/rec-repo/container-tools"
    tag: "1.0.7"


install:
  - exec:
      description: "Install Infra Charts"
      command: ./install.sh

#upgrade:
#  - exec:
#      description: "World 2.0"
#      command: ./helpers.sh
#      arguments:
#        - upgrade

uninstall:
  - exec:
      description: "Uninstall Infra Charts"
      command: ./uninstall.sh

# See https://porter.sh/wiring/#credentials
#credentials:
#  - name: kubeconfig
#    path: /root/.kube/config
```
