### ISSUE TITLE
schema should allow for mixin configuration

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1341]
## Describe the bug
When I declare a mixin and define configuration for it, VS Code decides that it is invalid.

![Screen Shot 2020-10-23 at 10 33 43 AM](https://user-images.githubusercontent.com/1368985/97023637-69e75280-151b-11eb-91b8-f9fc7986b135.png)

## To Reproduce

1. Create a porter.yaml
2. Declare a mixin with configuration:
    ```yaml
    mixins:
      - kubernetes:
          clientVersion: v1.15.5
    ```
3. Open it in VS Code and note the dreaded red squiggles

## Expected behavior
Ideally autocomplete for the mixin config (not supported yet). Otherwise it should at least not complain.

## Version
```
$ porter version
porter v0.29.1 (2e0f3648)
```
