### ISSUE TITLE
Suggestions on porter.yaml format

### ISSUE THREAD

**Issue by RomainMuller** [getporter/porter#136]
Hello,

Following a chat we had with @squillace, here's a quick dump of some observations/suggestions from the [AWS CDK](https://GitHub.com/awslabs/aws-cdk) team on the format of the `porter.yaml` file (based on going over the [azure-mysql-wordpress/porter.yaml](https://github.com/deislabs/porter/blob/master/examples/azure-mysql-wordpress/porter.yaml) example).

1. The `parameters` and `outputs` (and probably `credentials`) sections use arrays of objects, which makes it easy to define an entity with the same `name` multiple times. The unique-ness of the `name` would be better conveyed by representing those as maps (that requires less typing, too):
   ```yaml
   parameters:
     mysql_user:
       type: string
       default: azureuser
     mysql_password:
       type: string
       default: '!Th1s1s4p4ss!' # Or is it?
     database_name:
       type: string
       default: wordpress
   # ...
   install:
     - description: 'Create Azure MySQL'
        # ...
        outputs:
          MYSQL_HOST: MYSQL_HOST # or { key: MYSQL_HOST }
   ```
2. The variable references (`bundle.parameters.<name>`) would offer more flexibility (in the tooling) if they were modeled using an interpolation-like notation (e.g: `${bundle.parameters.<name>}`). Allows reducing the coupling between outputs of one step and input to another by allowing expressions (that would be computed by tooling) such as:
   ```yaml
   externalDatabase.jdbcUrl: |-
     jdbc:mysql://${bundle.outputs.mysql_host}:${bundle.parameters.mysql_port}/${bundle.parameters.database_name}
   ```
