### ISSUE TITLE
Can't default a file parameter with a filepath

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1386]
## Describe the bug
This is a gap in our implementation of the custom `file` parameter type. The underlying type is actually a base64 encoded string. Currently that is accidentally leaked to the user by `default` which doesn't accept a filepath, only `""` or a base64 encoded string.

## To Reproduce
1. Create a bundle with a file type parameter
2. Make the parameter optional by specifying a default
3. Try to run the bundle and you get an error.

```yaml
parameters:
- name: myparam
  type: file
  default: defaultParam.txt # located in the bundle at /cnab/app/defaultParam.txt
```
## Expected behavior

The default value should be read from filepath specified (where the file is stored in the invocation image). The filepath may be an empty string, in which case the file should not be read, relative or absolute. If relative, it should be resolved using `/cnab/app` as the working directory.

## Porter Command and Output
```
$ porter install

Error: unable to decode parameter publicIP: illegal base64 data at input byte 63
Error: 1 error occurred:
	* container exit code: 1, message: <nil>
```

## Version

v0.30.1
