### ISSUE TITLE
Porter build does not validate mixin syntax

### ISSUE THREAD

**Issue by MikkelHegn** [getporter/porter#1402]
## Describe the bug
I misspelled 'arguments' in an exec mixin command

```
  - exec:
      description: 'Unzip app directory'
      command: unzip
      argumnets:
        - output/webapi.zip
      flags:
        d: webapp
```

This wasn't caught during build, and the execution resulted in this command being executed `unzip -d webapp`

## Expected behavior
I would expect `porter build` to fail or warn when there are unknown mixin commands.

## Version
Copy the output of `porter version` below
porter v0.30.1 (2931a5c3)
