### ISSUE TITLE
Add working directory to mixins

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1403]
**Is your feature request related to a problem? Please describe.**
I want to run a command from a particular directory in my bundle

**Describe the solution you'd like**
I want a new field added to mixins where I can set the working directory. For example:

```yaml
exec:
  description: "Run ls in /tmp"
  command: bash
  dir: /tmp
  flags:
    c: ls
```

**Describe alternatives you've considered**
* At first we thought we could just use cd in an exec stanza and then run our command in the next stanza, but the changes made by cd do not persist between mixin executions.
* A workaround is ... a helper script which isn't porter-ish.

**Additional context**
I am typing this up for @squillace ❤️
