### ISSUE TITLE
Port Terraform Output to Helm install/upgrade

### ISSUE THREAD

**Issue by kickthemooon** [getporter/porter#1438]
**What is your question?**
Can Porter help me use Terraform output values with Helm install/upgrade without needing to transfer/translate my already existing terraform/helm ts's/yaml's to porter yaml?

note: 
I don't know what outputs there might be

**Where have you looked already to figure this out?**
docs, google

**Comment by carolynvs** [comment]
Hi, @kickthemooon! Let's walk through how you can combine porter, helm and terraform.

The porter.yaml file would contain high level calls to the terraform and helm cli. You don't rewrite any existing config files for either. What porter helps you do is connect the outputs from terraform to variables in helm.

Here is a made up example

```yaml
mixins:
  - helm
  - terraform

parameters:
  - name: tfstate
    type: file
    path: /cnab/app/terraform.tfstate
    source:
      output: tfstate

outputs:
  - name: tfstate
    type: file
    path: /cnab/app/outputs/terraform.tfstate

install:
  - terraform:
      description: "Install Something"
      input: false
      outputs:
      - name: service_endpoint
      - name: tfstate
        path: /cnab/app/outputs/terraform.tfstate
  - helm:
      description: "Install something that uses the service"
      name: somestuff
      chart: ./charts/mystuff
      version: v1.2.3
      namespace: mystuff
      set:
        webhook_url: "{{ bundle.outputs.service_endpoint }}"
```

In the first step of the install action, the Terraform mixin for Porter takes an output generated by Terraform and makes it available to Porter. Subsequent steps can access it with "{{bundle.outputs.OUTPUT_NAME}}".
In the second step, the Helm mixin for Porter runs `helm upgrade --install` and sets a chart variable using the output generated by Terraform.

The example above also stores the tfstate file (using the tfstate parameter and outputs) between executions of porter, so that you do not need to use a remote backend.

I just dump a bunch of info and realized that this would make a great example bundle. I'll see about writing one up but please let me know if you have any questions or need help making this work.
