### ISSUE TITLE
How to define object parameters with complex validation

### ISSUE THREAD

**Issue by cy-ddg** [getporter/porter#1459]
I am trying to define parameters that use the full power of the available JSONSchema validations available in the [CNAB spec](https://github.com/cnabio/cnab-spec/blob/cnab-core-1.0/101-bundle-json.md#definitions), but so far I have only middling success.

The following parameter definition
```yaml
parameters:
- name: values
  type: object
  properties:
    replicaCount:
      $id: '#/properties/replicaCount'
      type: integer
```
builds successfully but trying to set the parameter value on install like this
```yaml
parameters:
- name: values
  source:
    value: '{"replicaCount": 3}'
```
results in this error on running the install command:
```
Error: invalid parameters: unable to convert parameter's values value {"replicaCount": 3} to the destination parameter type object: invalid definition
```

A parameter definition like
```yaml
parameters:
- name: values
  type: object
  additionalProperties:
    type: string
```
does not even build and fails with the error:
```
Error: 1 error occurred:
	* encountered error while validating parameter values: unable to load schema: json: unsupported type: map[interface {}]interface {}
```

So my question is this: Am I doing something wrong or is this a limitation of the current implementation?

**Comment by vdice** [comment]
Thanks for bring this to our attention @cy-ddg .  Your approach above looks sound.  This definitely appears to be a bug in Porter.

**Comment by vdice** [comment]
We can close this once the cnab-go [fix](https://github.com/cnabio/cnab-go/pull/251) (or similar) is integrated into Porter.

**Comment by vdice** [comment]
I can confirm that this issue is fixed as of https://github.com/getporter/porter/commit/ed52bc1dbbfd9c99c356d1cda7633abf7fcae4aa on the v1 branch.

**Comment by carolynvs** [comment]
I am working on getting a build out of our v1 prerelease so that people can try this out. I'm going to close this issue since we have a fix merged, and will send out an announcement when I have a v1 build ready for people to try out.

Make sure to join our [mailing list](https://porter.sh/mailing-list) or [slack](https://porter.sh/community/#slack) to know when a build is ready to test.

**Comment by carolynvs** [comment]
This has been fixed in the [v1.0.0-alpha.2](https://github.com/getporter/porter/releases/tag/v1.0.0-alpha.2) prerelease. Please give it a try and let us know if you run into any problems!

**Comment by cy-ddg** [comment]
The new version looks very good! The example above is working now. I've found one more problem though when trying to define an array parameter with a specific schema for the items:
```yaml
parameters:
  - name: values
    type: array
    items:
      type: integer
```
This builds successfully but trying to install it with the following parameters:
```json
{
  "parameters": [
    {
      "name": "values",
      "source": {
        "value": "[]"
      }
    }
  ]
}
```
I get the following error message:
```
Error: 1 error occurred:
	* encountered error while validating parameter values: unable to load schema: json: unsupported type: map[interface {}]interface {}


Error: 1 error occurred:
	* container exit code: 1, message: <nil>
```

But besides that it is working pretty well. Good job!
