### ISSUE TITLE
Rearrange dependencies syntax in porter.yaml

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1570]
We know that we want to change the dependencies structure to allow for a "provides" section. As long as we are having a 1.0, let's make the change to "requires" now so that when we roll out dependencies it's not another breaking change.

```yaml
dependencies:
  - name: mysql
     reference: mysql:v1
```

to 

```yaml
dependencies:
  requires:
    - name: mysql
       reference: mysql:v1
```
