### ISSUE TITLE
Support directly writing an output to the filesystem or setting an environment variable

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1725]
When terraform creates an output, for example a password or a kubeconfig file, in order to use it in the same action, I sometimes have to write the file out myself to the filesystem, or get it into an environment variable so that the next step, can consume it.

Right now I workaround this by adding an exec call to put the output where I need it. But mixins can't affect environment variables!

It would be great if Porter's exec builder had support for outputs that need to be persisted for immediate use.

```yaml
install:
  - terraform:
       outputs:
          - name: kubeconfig
             destinationFile: /root/.kube/config
          - name: token
             destinationEnv: CLOUD_TOKEN
```

Writing to a file is straightforward, we can add another output handler interface and implement it similar to the others. https://github.com/getporter/porter/tree/main/pkg/exec/builder

For saving an environment variable, we can have the output handler write to a specially named file location, perhaps in `context.MixinOutputsDir`/_env, and when porter is done executing the mixin and [reads the outputs](https://github.com/getporter/porter/blob/a4694cd7347785676642f6eb5804ea9a830c3e9a/pkg/runtime/runtime.go#L206),  create env vars from the file contents.
