### ISSUE TITLE
Cannot specify default values for 'object' type parameters

### ISSUE THREAD

**Issue by cy-ddg** [getporter/porter#1738]
Using v1.0.0-alpha.2 I cannot specify a default value for object type parameters.

```yaml
parameters:
  - name: values
    default: {}
    type: object
```
results in the following error when trying to install:
```
Error: 1 error occurred:
	* encountered error while validating parameter values: unable to load schema: json: unsupported type: map[interface {}]interface {}
```

```yaml
parameters:
  - name: values
    default: ""
    type: object
```
results in the following error when trying to build the bundle:
```
Error: 1 error occurred:
	* encountered an error validating the default value  for parameter "values": type should be object, got string
```
