### ISSUE TITLE
Allow replacing variables in build-time sections

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1746]
Some sections of the porter.yaml are embedded into the bundle at build time:

* bundle metadata such as description, custom
* images section that defines referenced images
* mixins section
* parameters section

It would be useful to be able to reference the bundle template variables from these sections and have them replaced during build. A common ask is for something like this:

```yaml
custom: 
  appVersion: v0.2.1

images:
  myapp:
    repository: "me/myapp"
    tag: "{{ bundle.images.custom.appVersion }}"

parameters:
  - name: appVersion
     type: string
     default: "{{ bundle.images.custom.appVersion }}"
```

This also brings up an inconsistency in our template variable names, which was first noted in #1571. Related issues are: #1002, #319.
