### ISSUE TITLE
Allow using secrets and env vars in Porter's config file

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1763]
When I specify the connection string or any sensitive values in Porter's config file, I want to be able to reference a secret or environment variable instead of hard-coding them in the config file. The goal is to eliminate sensitive values from the config file.

The azure plugin already reads from env vars, but it seems like a burden to make each plugin solve this problem, or does it help solve resolving secrets.

Here are a couple ideas for referencing an env var or secret:

**Smoosh in a protocol**
pros: you edit the same url entry as you did before
cons: it could conflict with the format required by the plugin. not easy to autocomplete
```toml
[[storage]]
  name = "cosmos"
  plugin = "mongodb"

  [storage.config]
    url = "secret://my-secret-with-a-connstr"
    url = "env://MYENV
```

**Add extra config prefixes**
pros: 🤷‍♀️
cons: could conflict with plugin's config keys they want to use
```toml
[[storage]]
  name = "cosmos"
  plugin = "mongodb"

  [storage.config]
    secret-url = "my-secret-with-a-connstr"
    env-url = "MYENV"
```

**Specify replacements**
pros: very specific, no chance of conflicting
cons: extra config sections, may be more confusing to people
```toml
[[storage]]
  name = "cosmos"
  plugin = "mongodb"

  [storage.secrets]
    url = "my-secret-with-a-connstr"

  [storage.env]
    url = "MYENV"
```

**Specify replacements**
pros: very specific, no chance of conflicting
cons: extra config sections, may be more confusing to people
```toml
[[storage]]
  name = "cosmos"
  plugin = "mongodb"

  [[storage.replacements]]
    type = "secret"
    url = "my-secret-with-a-connstr"

  [[storage.replacements]]
    type = "env"
    url = "MYENV"
```

**Comment by carolynvs** [comment]
I have another alternative. We can use the same templating in the config file that we do in porter.yaml. And then use this opportunity to try out some of the improved template deliminator suggested in #316, for example `value: ${bundle.parameter.foo}`

The config file could look like this then:

```toml
[[storage]]
  name = "cosmos"
  plugin = "mongodb"

  [storage.config]
    url = "${secret.porter-db-url}"
```

It would use the same dot notation as porter.yaml does now:

* ${secret.KEY}
* ${env.NAME}

If we like it, we can use the new templating technique in porter.yaml for v1.
