### ISSUE TITLE
Problem executing docker-compose mixin on windows

### ISSUE THREAD

**Issue by dberardo-com** [getporter/porter#1784]
## The bug

porter install --allow-docker-host-access fails (see log below)

Running docker desktop on windows. all my docker commands including compose run without any problem. Porter cannot bind to the docker_host.

## Tentative solution

i have tried to set an evn variable DOCKER_HOST to point to the tcp socket but porter seems to ignore that variable completely. I have also tried to define it as a credential or param inside the bundle but it does not work.

## Log
here the log:

````
Error: unable to instantiate driver: allow-docker-host-access was specified but could not detect a local docker daemon running by checking for /var/run/docker.sock

**Comment by carolynvs** [comment]
Thanks for reporting this. We'll need to look into how to expose the docker socket on Windows. This looks promising https://stackoverflow.com/a/41005007

If you want to try to work around this, you'd need to figure out how to expose the docker host endpoint to a container running on that host (this is called Docker out of Docker, or DooD). For example, if you knew that your docker host endpoint is "tcp://192.168.59.103:2375", the trick is how to get the container to be able to resolve that ip address (because if your endpoint is localhost, that's not going to work).

**Comment by dberardo-com** [comment]
For now i use this workaround to install and test apps:


```
version: "3"

services:
  porter:
    container_name: porter
    image: docker
    volumes:
      - ./my-app:/home
      - //var/run/docker.sock:/var/run/docker.sock
    command: sleep 100000
```
once inside the container i install curl, porter and the app i am working on

However, it would be nice to be able to simply "tell" porter to look for another DOCKER_HOST on my windows machine, that would much less cumbersome

**Comment by dberardo-com** [comment]
on the same line: i am pulling images from a private docker repo. should i login onto that repo via an "exec" mixin or is there a better way to do that ?

**Comment by carolynvs** [comment]
Here's a blog post that explains how to use the docker mixin to build and publish images inside a bundle.

https://porter.sh/blog/docker-mixin-blog-post/

**Comment by dberardo-com** [comment]
thanks @carolynvs , i already knew that page. In fact i believe to have gone through most of the docker / docker-compose related documentation of porter in the past few days :D  

I have managed to setup a dev environment to use porter, and so far i was able to install/uninstall/publish the bundle successfully on a Windows machine.

I will share the 2 key steps with the community:

0. create an entrypoint.sh file:

```
#!/usr/bin/env bash
set -euo pipefail

curl -L https://cdn.porter.sh/latest/install-linux.sh | bash # install porter
cat "export PATH=$PATH:~/.porter" >> /root/.bashrc
````

1. setup porter in a docker container:

```
version: "3"

services:
  porter:
    container_name: porter
    image: docker
    working_dir: /home/work/app
    volumes:
      - ./my-app:/home/work/app
      - ./entrypoint.sh:/home/work/app/entrypoint.sh
      - //var/run/docker.sock:/var/run/docker.sock
    entrypoint: sh /home/work/app/entrypoint.sh
    command: /bin/sh -c "source /root/.bashrc && sleep 100000"
````

2. create helper.sh script in `./my-app` directory [credits](https://github.com/getporter/docker-compose-mixin/blob/main/examples/dockervolume/helpers.sh):

````
#!/usr/bin/env bash
set -euo pipefail

docker_login() {
    echo 'my_registry_password' | docker login private.registry.com --password-stdin --username myusername
}
````

3. add this lines to porter.yaml file:

````
mixins:
  - exec
  - docker-compose
  - docker

publish:
  - exec:
      description: "Logging into docker"
      command: ./helpers.sh
      arguments:
        - docker_login
  - exec:
      description: "Publishing bundle"
      command: porter publish
````

4. run docker-compose up -d and then "exec" in container, run the "source /root/.bashrc" file and then your are ready to run porter install commands
