### ISSUE TITLE
Do not allow repeats of credential or parameter sets on an installation

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1795]
## Describe the bug
I don't know how the data got into this state. I guess I can install a bunch even when the last install worked.

Now when I look at the installation it has repeated copies of the credential sets used:

```yaml
schemaVersion: 1.0.0
name: operator
namespace: operator
created: 2021-10-11T11:48:29.598255-05:00
modified: 2021-10-11T11:48:29.598255-05:00
bundleRepository: localhost:5000/porter-operator
bundleTag: canary
parameters:
  namespace: test
credentialSets:
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
  - kind
status:
  runId: 01FHX42QBPE8KNTYVD677WE8DH
  action: install
  resultId: 01FHX42RSJV5KD4W3RQ5RJT5CA
  resultStatus: failed
  installationCompleted: true
  bundleReference: localhost:5000/porter-operator:canary
  bundleVersion: 0.2.0-19-g0519cf2
  bundleDigest: sha256:26e6b58ad3fc4138afe46fb2bd0f6db73c9ab182bc95ccadfa241c836ec652be
_calculated:
  resolvedparameters: []
```
## To Reproduce
1. Run `...`
2. Use this porter.yaml from this repository or gist
3. Run this porter command `...`

## Expected behavior
Porter should cleanup the parameter and credential set list on an installation so that only unique values are kept.

## Version
```
porter v1.0.0-alpha.3-48-g6266cf4f (6266cf4f)
```
