### ISSUE TITLE
Consolidate bundle reference into a single field on installation

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1798]
The installation document looks like this currently, where the bundleReference is required and one of the bundleVersion, bundleDigest or bundleTag are required too.

```yaml
name: hello
bundleReference: getporter/porter-hello
bundleVersion: 0.1.1
bundleDigest: sha256:abc123
bundleTag: latest
```

As I'm working on the operator, I realized that we could consolidate all the bundle fields into a single node to improve clarity:

```yaml
name: hello
bundle:
  repository: getporter/porter-hello
  version: 0.1.1
---
name: hello
bundle:
  repository: getporter/porter-hello
  digest: sha256:abc123
---
name: hello
bundle:
  repository: getporter/porter-hello
  tag: latest
```

This would be a breaking change for any existing stored data but now's the time, since we don't have to support migrations until our release candidate.
