### ISSUE TITLE
Persistent parameters

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1889]
Copied from https://github.com/getporter/porter/discussions/1672

### I want to remember the value used for the parameter during install and reuse it later. 
In the example below, here's what's required to persist a parameter and reuse it later. You need an output declared, and then a parameter that sources the output:

```yaml
parameters:
- name: resource-group
  type: string
  path: /cnab/app/resource-group
  source:
    output: resource-group
  applyTo:
  - install
  - upgrade
  - uninstall

outputs:
- name: resource-group
  path: /cnab/app/resource-group
```

In the case where we just want to remember a parameter value from action to action, here is a potential shorthand:
```yaml
parameters:
- name: resource-group
  type: string
  persistent: true
```

We already do something very similar to this in the implementation of state and we can implement this by using a similar technique by outputing the first definition to bundle.json in our cnab adapter when persistent = true.

Note that when we implement this feature, since it is a new field on the manifest schema, that the schema version must be incremented and the major version of porter must also be incremented. So if we don't do this by 1.0, it will cause a 2.0. Let's embrace big major versions and not get squeamish about it.
