### ISSUE TITLE
Auth error publishing a bundle that references an image

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#1908]
I was testing out #1901 and noticed that my test bundle was failing to publish. I tested on the v1 branch and it still failed to publish.

porter.yaml
```
name: single-bundle-test
version: 0.1.0
description: "An example Porter configuration"
registry: carolynvs

images:
  hello:
      description: "hello world"
      imageType: "docker"
      repository: "hello-world"
      digest: "sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4"
 
mixins:
  - exec

install:
  - exec:
      description: "Install Hello World"
      command: ./helpers.sh
      arguments:
        - install

upgrade:
  - exec:
      description: "World 2.0"
      command: ./helpers.sh
      arguments:
        - upgrade

uninstall:
  - exec:
      description: "Uninstall Hello World"
      command: ./helpers.sh
      arguments:
        - uninstall
```

```
porter build
porter publish
...
Starting to copy image carolynvs/single-bundle-test-installer:v0.1.0 to docker.io/carolynvs/single-bundle-test:v0.1.0...
Completed image carolynvs/single-bundle-test-installer:v0.1.0 copy
Starting to copy image hello-world@sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4 to docker.io/carolynvs/single-bundle-test:v0.1.0...
Failed to copy image hello-world@sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4: server message: insufficient_scope: authorization failed
2022-02-15T09:14:28.464-0600	error	error preparing the bundle with cnab-to-oci before pushing: server message: insufficient_scope: authorization failed
```

I edited the log lines so that it showed you the destination where the image was being pushed (though I'm not 100% certain the tag is accurately showing where it's being copied). 

I then tried with v0.38 and it worked.

```
porter publish
...
Starting to copy image carolynvs/single-bundle-test-installer:v0.1.0 to docker.io/carolynvs/single-bundle-test:v0.1.0...
Completed image carolynvs/single-bundle-test-installer:v0.1.0 copy
Starting to copy image hello-world@sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4 to docker.io/carolynvs/single-bundle-test:v0.1.0...
Completed image hello-world@sha256:f54a58bc1aac5ea1a25d796ae155dc228b3f0e11d046ae276b39c4bf2f13d8c4 copy
Bundle tag docker.io/carolynvs/single-bundle-test:v0.1.0 pushed successfully, with digest "sha256:1abf7c78f668f7ed0ee2b80bb847b6a529ae1995c601e18e78dd02dfbeee9f1c"
```

v1 and main use two different versions of cnab-to-oci. I think my change in this PR is incorrect and is immediately returning the first error instead of trying the other fixup methods? https://github.com/cnabio/cnab-to-oci/pull/113

Let's try using the same version of cnab-to-oci that main uses, and if that fixes it, I'll redo that PR.
