### ISSUE TITLE
Is there any known methods to release porter apps ?

### ISSUE THREAD

**Issue by LvffY** [getporter/porter#1935]
Hello

I'm building a porter app, and we're asking ourselves if there is any known methods for automatic release about our app (something like the [maven release plugin](https://maven.apache.org/maven-release/maven-release-plugin/) or the [zest.releaser python tool](https://github.com/zestsoftware/zest.releaser]).

For now, I think I'm going to try out the simple [bump2version](https://github.com/c4urself/bump2version). 

The features I'd like to see (at least) : 
- Version upgrade
- Commit & tag of the new version
- *Optionnaly* push the changes

The best option IMHO is a `porter release` command but an « official » method documented could do the trick.

Please tell me if I missed something

Best regards

LvffY

**Comment by carolynvs** [comment]
The `porter build` command has a --version flag to let you set the version dynamically in your CI pipeline. What people usually do is use `git describe` to get the current version from git and then pass that value to the --version flag.

**Comment by LvffY** [comment]
Thanks @carolynvs for your explanation ! 

For anyone that could be struggled with the same question that I had, I came up with the following solutions : 

## The (Azure DevOps) pipeline : the global method

 <details>
  <summary>Click to expand</summary>
  
  ```yaml
stages:
  - stage: snapshot
    displayName: Build snapshot porter app
    ## Build this only on dev branches
    condition: not(startsWith(variables['build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: snapshot
        displayName: Build snapshot porter app
        steps:
          - checkout: self
            persistCredentials: true
            displayName: "Checkout porter repo"
            

          - task: Docker@2
            displayName: Login to docker registry
            inputs:
              command: login
              containerRegistry: YOUR_DOCKER_REGISTRY_CONNECTION

          - task: Bash@3
            displayName: 'Install porter'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                curl -L https://cdn.porter.sh/latest/install-linux.sh | bash
                echo "##vso[task.setvariable variable=PATH]${PATH}:~/.porter"

          - task: Bash@3
            displayName: 'Porter build'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                porter build

          - task: Bash@3
            displayName: 'Porter publish'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                porter publish --registry YOUR_DOCKER_REGISTRY_URL

  - stage: release
    displayName: Build release porter app
    ## Build this only on release branches
    condition: startsWith(variables['build.SourceBranch'], 'refs/heads/master')
    dependsOn: []
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: release
        displayName: Build release porter app
        steps:
          - checkout: self
            persistCredentials: true
            displayName: "Checkout porter repo"

          # Use Python version
          # Use the specified version of Python from the tool cache, optionally adding it to the PATH
          - task: UsePythonVersion@0
            displayName: Install python
            inputs:
              versionSpec: '3.9'

          - task: Docker@2
            displayName: Login to PROD ACR
            inputs:
              command: login
              containerRegistry: YOUR_DOCKER_REGISTRY_CONNECTION

          - task: Bash@3
            displayName: 'Install porter'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                curl -L https://cdn.porter.sh/latest/install-linux.sh | bash
                echo "##vso[task.setvariable variable=PATH]${PATH}:~/.porter"

          - task: Bash@3
            displayName: 'Porter build'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                porter build

          - task: Bash@3
            displayName: 'Porter publish'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                porter publish --registry YOUR_DOCKER_REGISTRY_URL

          - task: Bash@3
            displayName: 'Update app version'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                pip install --upgrade pip
                pip install --upgrade bump2version pyyaml
                ## This line is probably the most ugly, but do the trick ... Anyone with a better idea is welcome :)
                version=$(python3 -c "import yaml; print(yaml.load(open('porter.yaml'), Loader=yaml.FullLoader)['version'])")
                bump2version --config-file bumpversion.cfg --current-version $version patch porter.yaml
                git push origin HEAD:${{ variables['build.sourceBranch'] }} --tags
  ```
</details>

## The **bumpversion.cfg** : the specific configurations

<details>
  <summary>Click to expand</summary>
  
  ```ini
[bumpversion]
commit = True
tag = True
tag_name = v{current_version}
message = "Bump version: {current_version} → {new_version} [ci skip]"
  ```

***N.B:*** The `[ci skip]` tag is ot avoid trigger a release when we push the commit made during the current release.
</details>
