### ISSUE TITLE
Wire parameters and credentials from the bundle into the mixin

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#20]
```
install:
  - description: "Install Wordpress Helm Chart"
    helm:
      name:
        source: bundle.name
      chart: stable/wordpress
      parameters:
        externalDatabase.database:
          source: bundle.parameters.database-name
        externalDatabase.host:
          source: bundle.credentials.dbhost
        externalDatabase.user:
          source: bundle.credentials.dbuser
        externalDatabase.password:
          source: bundle.credentials.dbpassword
```
