### ISSUE TITLE
Define custom annotations for a bundle

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2018]
Some registries support [well-defined annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) such as 

`org.opencontainers.image.source = "https://github.com/getporter/examples"`

In the example above, that associates the bundle with a particular repository and affects how it is displayed in the registry. 

What if we supported a way for people to set annotations through the porter.yaml file?

```yaml
# porter.yaml
annotations:
  org.opencontainers.image.source: "https://github.com/getporter/examples"
```
