### ISSUE TITLE
Be able to run command after porter tasks

### ISSUE THREAD

**Issue by LvffY** [getporter/porter#2044]
**Is your feature request related to a problem? Please describe.**

It would be great to have a feature that would enable users to submit command that would be run after the lines that porter adds.

In my use case, I have many ansible command to run. These playbooks depends on the [ansible azure collection](https://github.com/ansible-collections/azure) that requires, when installed to run an additional pip command `pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt`

To achieve this, I need to run (in order) the following steps : 

- Download playbooks & install Ansible
- Install azure collection through `ansible-galaxy`
- Run `pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt`

For now, you can imagine that I have the following files : 

- **porter.yaml**

<details>
  <summary>Click to expand!</summary>

```yaml
name: name
version: version
description: "Bundle to deploy our apps"
registry: registry
dockerfile: Dockerfile.tmpl
schemaVersion: 1.0.0-alpha.1

mixins:
  - exec
  - ansible:
      otherPipDependencies:
        - virtualenv
        - psycopg2
        - openshift

install: 
  - ansible:
      description: "Install ansible collection"
      galaxy:
        arguments:
          - "collection"
          - "install"
        flags:
          requirements-file: requirements.yml

  - exec:
      description: "Install ansible azure pip dependencies"
      command: pip
      arguments:
        - "install"
      flags:
        upgrade: ""
        requirement: "/home/nonroot/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt"

  - ansible:
      description: "Finally, run playbook"
      playbook:
        arguments:
          - "install.yml"

upgrade:
  - ansible:
      description: "Install ansible collection"
      galaxy:
        arguments:
          - "collection"
          - "install"
        flags:
          requirements-file: requirements.yml

  - exec:
      description: "Install ansible azure pip dependencies"
      command: pip
      arguments:
        - "install"
      flags:
        upgrade: ""
        requirement: "/home/nonroot/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt"

  - ansible:
      description: "Finally, run playbook"
      playbook:
        arguments:
          - "upgrade.yml"

uninstall:
  - ansible:
      description: "Install ansible collection"
      galaxy:
        arguments:
          - "collection"
          - "install"
        flags:
          requirements-file: requirements.yml

  - exec:
      description: "Install ansible azure pip dependencies"
      command: pip
      arguments:
        - "install"
      flags:
        upgrade: ""
        requirement: "/home/nonroot/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt"

  - ansible:
      description: "Finally, run playbook"
      playbook:
        arguments:
          - "uninstall.yml"
```
</details>

- **Dockerfile.tmpl**

<details>
  <summary>Click to expand!</summary>

```dockerfile
# syntax=docker/dockerfile-upstream:1.4.0
FROM ubuntu:22.04

## Git token to use to clone
ARG GIT_TOKEN
## Git reference to clone our playbook repository
ARG GIT_REF

## Git script to generate password non interactively
## See https://git-scm.com/docs/gitcredentials#_requesting_credentials
ENV GIT_ASKPASS=$BUNDLE_DIR/git_askpass.sh

RUN apt-get update && \
    ## Install all necessary tools
    apt-get install -y --no-install-recommends wget gnupg2 python3 python3-dev python3-pip git libpq-dev build-essential apt-transport-https ca-certificates &&  \
    ## Ensure linux packages are up-to-date \
    apt-get dist-upgrade -y && \
    ## Clean up image
    apt-get autoremove &&  \
    apt-get autoclean

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR

## Clone playbook repositories
RUN chmod +x $BUNDLE_DIR/*.sh && \
    git clone --branch $GIT_REF -- REPO_URL REPO_DIRECTORY && \
    rm $GIT_ASKPASS
```
</details>

- which leads to the following final **Dockerfile** : 

<details>
  <summary>Click to expand!</summary>

```dockerfile
# syntax=docker/dockerfile-upstream:1.4.0
FROM ubuntu:22.04

## Git token to use to clone
ARG GIT_TOKEN
## Git reference to clone our playbook repository
ARG GIT_REF

## Git script to generate password non interactively
## See https://git-scm.com/docs/gitcredentials#_requesting_credentials
ENV GIT_ASKPASS=$BUNDLE_DIR/git_askpass.sh

RUN apt-get update && \
    ## Install all necessary tools
    apt-get install -y --no-install-recommends wget gnupg2 python3 python3-dev python3-pip git libpq-dev build-essential apt-transport-https ca-certificates &&  \
    ## Ensure linux packages are up-to-date \
    apt-get dist-upgrade -y && \
    ## Clean up image
    apt-get autoremove &&  \
    apt-get autoclean

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR

## Clone playbook repositories
RUN chmod +x $BUNDLE_DIR/*.sh && \
    git clone --branch $GIT_REF -- REPO_URL REPO_DIRECTORY && \
    rm $GIT_ASKPASS
ARG BUNDLE_DIR
ARG BUNDLE_UID=65532
ARG BUNDLE_USER=nonroot
ARG BUNDLE_GID=0
RUN useradd ${BUNDLE_USER} -m -u ${BUNDLE_UID} -g ${BUNDLE_GID} -o

# exec mixin has no buildtime dependencies

RUN pip install --upgrade --no-cache-dir pip && \
	pip install --upgrade --no-cache-dir setuptools wheel && \
	pip install --upgrade --no-cache-dir 'ansible' 'virtualenv' 'psycopg2' 'openshift'  
	
ENV HELM_EXPERIMENTAL_OCI=1
RUN rm ${BUNDLE_DIR}/porter.yaml
RUN rm -fr ${BUNDLE_DIR}/.cnab
COPY --link .cnab /cnab
RUN chgrp -R ${BUNDLE_GID} /cnab && chmod -R g=u /cnab
USER ${BUNDLE_UID}
WORKDIR ${BUNDLE_DIR}
CMD ["/cnab/app/run"]
```
</details>

Based on that, it would be great to have a way to write our template and tell porter to add some additional lines at the end of our docker file to have something like : 

<details>
  <summary>Click to expand!</summary>

```dockerfile
# syntax=docker/dockerfile-upstream:1.4.0
FROM ubuntu:22.04

## Git token to use to clone
ARG GIT_TOKEN
## Git reference to clone our playbook repository
ARG GIT_REF

## Git script to generate password non interactively
## See https://git-scm.com/docs/gitcredentials#_requesting_credentials
ENV GIT_ASKPASS=$BUNDLE_DIR/git_askpass.sh

RUN apt-get update && \
    ## Install all necessary tools
    apt-get install -y --no-install-recommends wget gnupg2 python3 python3-dev python3-pip git libpq-dev build-essential apt-transport-https ca-certificates &&  \
    ## Ensure linux packages are up-to-date \
    apt-get dist-upgrade -y && \
    ## Clean up image
    apt-get autoremove &&  \
    apt-get autoclean

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR

## Clone playbook repositories
RUN chmod +x $BUNDLE_DIR/*.sh && \
    git clone --branch $GIT_REF -- REPO_URL REPO_DIRECTORY && \
    rm $GIT_ASKPASS
ARG BUNDLE_DIR
ARG BUNDLE_UID=65532
ARG BUNDLE_USER=nonroot
ARG BUNDLE_GID=0
RUN useradd ${BUNDLE_USER} -m -u ${BUNDLE_UID} -g ${BUNDLE_GID} -o

# exec mixin has no buildtime dependencies

RUN pip install --upgrade --no-cache-dir pip && \
	pip install --upgrade --no-cache-dir setuptools wheel && \
	pip install --upgrade --no-cache-dir 'ansible' 'virtualenv' 'psycopg2' 'openshift'  
	
ENV HELM_EXPERIMENTAL_OCI=1
RUN rm ${BUNDLE_DIR}/porter.yaml
RUN rm -fr ${BUNDLE_DIR}/.cnab

### THIS WOULD BE ADDED
RUN my-other-command
###

COPY --link .cnab /cnab
RUN chgrp -R ${BUNDLE_GID} /cnab && chmod -R g=u /cnab
USER ${BUNDLE_UID}
WORKDIR ${BUNDLE_DIR}
CMD ["/cnab/app/run"]
```
</details>

**Describe the solution you'd like**

The simpler solution I can think about is to put the porter command lines **before** the lines put in the template docker file. *Of course, we would have be careful of the `FROM base-image` line.

It think this could be possible because all porter plugins are supposed to be self-supporting so added the lines at any point would lead to the same output.

**Describe alternatives you've considered**

These commands could be run during the porter execution tasks (install,upgrade etc.) but this enforces us to repeat the lines. And in my case, it's more a build step than an execution step i.e do

- At build time : 
  - Download playbooks & install Ansible
- At execution time : 
  - Install azure collection through `ansible-galaxy`
  - Run `pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt`

**Additional context**

We could also imagine this kind of use case for helm, where we'd want to install helm charts/plugins during build rather than during execution.

**Comment by LvffY** [comment]
Another use case : with porter not using root user anymore (another great feature :)), we can't install `pip` packages in the root system. 

So it will install them in `$HOME/.local.bin`. And this path is not in the `PATH` environment variable.

So right now, we could want to add this export after the user non root was created.

**Comment by LvffY** [comment]
@carolynvs Thanks for your quick answer :)

This is exactly what I needed, I missed it in the docs 😞 

For anyone who fall into this issue, I managed to use the porter tokens to finally come up with the following solutions

- **porter.yaml**

<details>
  <summary>Click to expand!</summary>

```yaml
name: name
version: version
description: "Bundle to deploy our apps"
registry: registry
dockerfile: Dockerfile.tmpl
schemaVersion: 1.0.0-alpha.1

mixins:
  - exec
  - ansible:
      otherPipDependencies:
        - virtualenv
        - psycopg2
        - openshift

install: 
  ## Note that there is no more dupplicated code, this is passed at run time 🎉
  - ansible:
      description: "Finally, run playbook"
      playbook:
        arguments:
          - "install.yml"

upgrade:
  ## Note that there is no more dupplicated code, this is passed at run time 🎉
  - ansible:
      description: "Finally, run playbook"
      playbook:
        arguments:
          - "upgrade.yml"

uninstall:
  ## Note that there is no more dupplicated code, this is passed at run time 🎉
  - ansible:
      description: "Finally, run playbook"
      playbook:
        arguments:
          - "uninstall.yml"
```
</details>


- **Dockerfile.tmpl**

<details>
  <summary>Click to expand!</summary>

```dockerfile
# syntax=docker/dockerfile-upstream:1.4.0
FROM ubuntu:22.04

## Porter init steps
## See https://release-v1.porter.sh/bundle/custom-dockerfile/#porter_init
# PORTER_INIT

## Git token to use to clone
ARG GIT_TOKEN
## Git reference to clone our playbook repository
ARG GIT_REF

## Git script to generate password non interactively
## See https://git-scm.com/docs/gitcredentials#_requesting_credentials
ENV GIT_ASKPASS=$BUNDLE_DIR/git_askpass.sh

RUN apt-get update && \
    ## Install all necessary tools
    apt-get install -y --no-install-recommends wget gnupg2 python3 python3-dev python3-pip git libpq-dev build-essential apt-transport-https ca-certificates &&  \
    ## Ensure linux packages are up-to-date \
    apt-get dist-upgrade -y && \
    ## Clean up image
    apt-get autoremove &&  \
    apt-get autoclean

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR

## Clone playbook repositories
RUN chmod +x $BUNDLE_DIR/*.sh && \
    git clone --branch $GIT_REF -- REPO_URL REPO_DIRECTORY && \
    rm $GIT_ASKPASS

## Porter mixins install
## See https://release-v1.porter.sh/bundle/custom-dockerfile/#porter_mixins
# PORTER_MIXINS

# This part was before dupplicated in each steps 🎉
## Install needed ansible collections
RUN ansible-galaxy collection install --requirements-file $BUNDLE_DIR/requirements.yml --collections-path $ANSIBLE_COLLECTIONS_PATH && \
    pip install --upgrade --requirement $ANSIBLE_COLLECTIONS_PATH/ansible_collections/azure/azcollection/requirements-azure.txt
```
</details>

From my side, you can close this ticket 😀
