### ISSUE TITLE
az mixin not parsing jsonPath output

### ISSUE THREAD

**Issue by KiPIDesTAN** [getporter/porter#2067]
## Describe the bug
I am trying to parse outputs from the az mixin with a simple jsonPath that I validated from jsonpath.com. When I run the code and parse for the output, the output is never created in the output map and the subsequent echo command to output what was captured fails.

I'm hoping it's something I'm missing in the syntax, but haven't been able to get this to work.

## To Reproduce

Step 1. Use porter.yaml file below. You'll need to have a working SPN and set the appropriate json 
porter.yaml file.
```
name: porter-hello
version: 0.1.1
description: "An example Porter configuration"
registry: getporter

mixins:
  - az
  - exec

credentials:
- name: azure-tenant
  description: Azure Tenant Name. e.g. something.onmicrosoft.com.
  env: AZURE_RM_TENANT
- name: azure-tenant-id
  description: Azure Tenant ID
  env: AZURE_RM_TENANTID
- name: azure-subscription-id
  description: Azure Subscription ID
  env: AZURE_SUBSCRIPTION_ID
- name: azure-client-id
  description: Azure SPN client ID (app ID) that can deploy various services to the targeted subscription
  env: AZURE_RM_CLIENTID
- name: azure-client-secret
  description: Azure SPN client secret
  env: AZURE_RM_SECRET

install:
  - az:
      description: "Login to Azure"
      arguments:
        - login
      flags:
        service-principal:
        username: " {{ bundle.credentials.azure-client-id}} "
        password: " {{ bundle.credentials.azure-client-secret}} "
        tenant: " {{ bundle.credentials.azure-tenant}} "
      outputs:
      - name: "cloudName"
        jsonPath: "$[0].cloudName"
  - exec:
      description: "echo"
      command: echo
      arguments:
        - "Cloud user: {{ bundle.outputs.cloudName }}"

uninstall:
  - exec:
      description: "Uninstall Hello World"
      command: echo
      arguments:
        - "Uninstalling"
```

2. Build porter and install
3. When porter installs, it logs in successfully, but doesn't capture the jsonPath. I have tried this with multiple az cli commands and they all have this issue.

## Expected behavior
The jsonPath above should capture the cloudName, which in the example below is "AzureCloud"

## Porter Command and Output
```
$ porter install --cred azure_creds --debug
Login to Azure
DEBUG name:    az
DEBUG pkgDir: /cnab/app/mixins/az
DEBUG file:     
DEBUG stdin:
install:
  - az:
      arguments:
        - login
      description: Login to Azure
      flags:
        password: ' ******* '
        service-principal: null
        tenant: ' ******* '
        username: ' ******* '
      outputs:
        - jsonPath: $[0].cloudName
          name: cloudName

/cnab/app/cnab/app/mixins/az/runtimes/az-runtime install --debug
DEBUG Parsed Input:
&az.Action{Name:"install", Steps:[]az.TypedStep{az.TypedStep{Description:"", TypedCommand:(*az.UserCommand)(0xc000346a80)}}}
/cnab/app az login --output json --password ******* --service-principal --tenant ******* --username *******
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "*******",
    "id": "something-something-something",
    "isDefault": true,
    "managedByTenants": [],
    "name": "something-something-something",
    "state": "Enabled",
    "tenantId": "*******",
    "user": {
      "name": "*******",
      "type": "servicePrincipal"
    }
  },
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "*******",
    "id": "*******",
    "isDefault": false,
    "managedByTenants": [
      {
       "tenantId": "something-something-something"
      }
    ],
    "name": "something-something-something",
    "state": "Enabled",
    "tenantId": "*******",
    "user": {
      "name": "*******",
      "type": "servicePrincipal"
    }
  }
]
=== Step Data ===
map[bundle:map[credentials:map[azure-client-id:******* azure-client-secret:******* azure-subscription-id:******* azure-tenant:******* azure-tenant-id:*******] custom:map[] dependencies:map[] description:An example Porter configuration images:map[] invocationImage:getporter/porter-hello-installer:v0.1.1 name:porter-hello outputs:map[] parameters:map[] version:0.1.1] env:map[AZURE_RM_CLIENTID:******* AZURE_RM_SECRET:******* AZURE_RM_TENANT:******* AZURE_RM_TENANTID:******* AZURE_SUBSCRIPTION_ID:******* CNAB_ACTION:install CNAB_BUNDLE_NAME:porter-hello CNAB_BUNDLE_VERSION:0.1.1 CNAB_CLAIMS_VERSION:1.0.0-DRAFT+b5ed2f3 CNAB_INSTALLATION_NAME:porter-hello CNAB_REVISION:01G392DVDV0JQ24YZJXTKYTSD7 HOME:/root HOSTNAME:67660a51bffd PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PORTER_DEBUG:true PORTER_HOME:/cnab/app PWD:/cnab/app SHLVL:0] installation:map[name:porter-hello]]
=== Step Template ===
exec:
  arguments:
    - 'Cloud user: {{ bundle.outputs.cloudName }}'
  command: echo
  description: echo

Error: unable to resolve step: unable to render step template exec:
  arguments:
    - 'Cloud user: {{ bundle.outputs.cloudName }}'
  command: echo
  description: echo
: Missing variable "cloudName"
Error: 1 error occurred:
        * container exit code: 1, message: <nil>

```

## Version
Copy the output of `porter version` below

porter version v0.38.11 (7db0ea7d)
az mixin - v0.7.2

My dev environment is WSL 2 w/the latest stable release of VSCode. Docker Desktop 4.7.1 (77678), and the latest az cli for Linux (2.36.0).
