### ISSUE TITLE
Add param/cred source for data that porter can resolve internally

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2226]
When we are running a dependency workflow, we need a way to pass the result of a bundle run to a bundle that runs later. Parameter and credential sets should support a new source `porter` that is resolved by porter, not a plugin.

```yaml
name: internal-ps-for-dep-workflow
parameters:
  - name: connStr
     source:
       porter: plan.tasks.mysql.outputs.connStr
```

I haven't settled on the exact format but the idea is that porter would be aware of the current workflow execution plan that the parameter/credential set is being used within, and can resolve outputs from the run that occurred within that execution plan. So in the above reference `plan.tasks.mysql.outputs.connStr`, Porter would intercept the source and resolve it without going through the plugin protocol. Porter can use its internal context to know which execution plan it is currently executing, then lookup the named task "mysql" within the plan, figure out the run and result id from that task (which must have already completed successfully) and then use those ids to lookup the output value.

This should only be internal functionality in Porter but not to end users at this time. So someone couldn't make a ps/cs that used the porter source for now.
