### ISSUE TITLE
Enable creating parameter/credentials using referenced bundles

### ISSUE THREAD

**Issue by joshuabezaleel** [getporter/porter#2300]
**Is your feature request related to a problem? Please describe.**
We have `--reference` flag for either parameter/credential `generate` command but we want to encourage people to use the combination of `create` and apply` command. 

**Describe the solution you'd like**
User can create new parameter/credential by referencing a bundle using `--reference` flag
```
porter parameters create --reference bundle
porter credentials create --reference bundle
```

**Describe alternatives you've considered**
`generate` command already have `--reference` flag but it's harder to explain what to type in response to the interactive prompts on our documentation site so we want to encourage people using `create` + `apply`. 

**Additional context**

**Comment by carolynvs** [comment]
Normally the create command creates the file using a template. When --reference is specified, it should instead populate the file with actual parameters/credentials from the bundle.

So `porter credentials create --reference ghcr.io/getporter/examples/credentials-tutorial:v0.3.0 mycreds.yaml` would create the following file:

```yaml
# Created from ghcr.io/getporter/examples/credentials-tutorial:v0.3.0
name: credentials-tutorial

# The namespace in which the credential set is defined.
# Omit the namespace to define the credential set in the current current namespace.
namespace: NAMESPACE

# Optionally define labels which can be used for filtering. Labels must be string values.
labels:
  LABEL: LABEL_VALUE

# Credentials specify how Porter can resolve credentials when executing a bundle.
# Allowed sources are: value, path, env, secret, and command.
credentials:
  # Put the description of the credential/parameter in a comment like below
  # A GitHub Personal Access Token. Generate one at https://github.com/settings/tokens. No scopes are required.
  - name: github-token
    source:
      # TODO: Uncomment one source from below and remove the rest.
      # Use the specified value for the credential. Do not use "value" for sensitive data.
      value: credentialvalue
      # Resolve the credential value from the contents of the specified file.
      #path: /path/to/credential-path-file.txt
      # Resolve the credential value from the output of the specified command.
      #command: echo 'credential command'
      # Resolve the credential value from the value of the specified environment variable.
      #env: CREDENTIAL_ENV
      # Resolve the credential value from the secret store specified in your Porter configuration file.
      #secret: credential-secret
```
