### ISSUE TITLE
State file unpacking fails if an empty state file exists

### ISSUE THREAD

**Issue by sgettys** [getporter/porter#2307]
## Describe the bug
I'm getting the following error when trying to use a porter bundle that has "state" provided in the manifest when running in the operator:
could not create a new gzip reader for the statefile: unexpected EOF
This is when using "state" to store off terraform tfstate files ex:

state:
  - name: tfstate
    path: terraform/terraform.tfstate
  - name: tfvars
    path: terraform/terraform.tfvars.json
This works when setting the tfstate file as a bundle output and using it that way.
Running this on beta.2 in the operator

## To Reproduce
1. Install a porter bundle in the operator that has "state" defined in the porter.yaml

## Expected behavior
Porter should install successfully for bundles with "state" in the porter.yaml that run in the operator

## Version
Copy the output of `porter version` below
porter v1.0.0-beta.2 (b2f23785)

**Comment by VinozzZ** [comment]
Hey @sgettys , thanks for working out the fix for this! 
Feel free to remove the `WIP` in the PR title whenever this PR is ready for review

**Comment by VinozzZ** [comment]
Hey @sgettys , I just created a simple bundle just to make sure that I understand the scenario. Is this what you are trying to do? If not, do you mind to share your use case with me?
```yaml
schemaVersion: 1.0.0-alpha.1
name: examples/porter-hello
version: 0.2.0
description: "An example Porter configuration"
registry: ghcr.io/getporter

state:
  - name: magic_file
    path: magic.txt

mixins:
  - exec

install:
  - exec:
      description: "Install Hello World"
      command: touch
      arguments:
        - /cnab/app/magic.txt
  - exec:
      description: "Print magic"
      command: cat
      arguments:
        - magic.txt

```

This bundle seems to be working for me locally
