### ISSUE TITLE
Porter publish rebuild the image instead of just pushing it

### ISSUE THREAD

**Issue by LvffY** [getporter/porter#2391]
## Describe the bug

My porter bundle is correctly building. But for the build to pass correctly, I need to pass some `--build-arg` (in particular a `GIT_TOKEN`).

During my buid everything runs fine. Then during the publish, for no reason, the `porter publish` command tries to rebuid my image. Because I can't have `--build-arg` at this step, my build fails. 

I'm thinking of a bug here, because just set some retries on my task make it pass and runs correctly (i.e just push the image).

## To Reproduce

1. Run
```bash
curl -L https://cdn.porter.sh/latest/install-linux.sh | bash
export PATH=~/.porter
porter mixins install --url https://github.com/LvffY/ansible-mixin/releases/download ansible
porter mixins install --feed-url https://mchorfa.github.io/porter-helm3/atom.xml helm3
porter mixins install kubernetes
porter build --build-arg GIT_TOKEN="This is a secret for build time !" --build-arg BUNDLE_USER=porter
```
2. Use this porter.yaml & Dockerfile.tmpl

<details><summary>Dockerfile.tmpl</summary>
<p>

```Dockerfile
FROM ubuntu:20.04

## Porter init steps
## See https://porter.sh/bundle/custom-dockerfile/#porter_init
# PORTER_INIT

## Git token to use to clone
ARG GIT_TOKEN
## Mozilla SOPS version
ARG SOPS_VERSION=3.7.3

## Git script to generate password non interactively
## See https://git-scm.com/docs/gitcredentials#_requesting_credentials
ENV GIT_ASKPASS=$BUNDLE_DIR/git_askpass.sh \
    ## Ensure path contains python executable for the porter user
    PATH=$PATH:/home/${BUNDLE_USER}/.local/bin \
    ## Avoid noisy depreciation warnings in python libraries not under our responsabilities
    PYTHONWARNINGS="ignore" \
    ## Ensure Ansible will find installed collections
    ANSIBLE_COLLECTIONS_PATH="$BUNDLE_DIR/collections"

RUN apt-get update && \
    ## Install all necessary tools
    apt-get install -y --no-install-recommends wget gnupg2 python3 python3-dev python3-pip python3-venv git libpq-dev build-essential apt-transport-https ca-certificates &&  \
    ## Install SOPS
    wget https://github.com/mozilla/sops/releases/download/v$SOPS_VERSION/sops_${SOPS_VERSION}_amd64.deb && \
    dpkg -i sops_${SOPS_VERSION}_amd64.deb && \
    ## Ensure linux packages are up-to-date \
    apt-get dist-upgrade -y && \
    ## Because helm mixins install the executable under /usr/local/bin/helm3, we create a symbolic link to avoid too many configurations in our ansible playbooks.
    ## During the installation process, this link is broken.
    ## When helm mixins is installed this link will work.
    ln -sf /usr/local/bin/helm3 /usr/local/bin/helm && \
    ## Clean up image
    apt-get autoremove &&  \
    apt-get autoclean &&  \
    rm -rf /var/lib/apt/lists/* sops_${SOPS_VERSION}_amd64.deb

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR

## Clone playbook repositories
RUN echo "${GIT_TOKEN:?GIT_TOKEN is not set, please set it.}"

## Porter mixins install
## See https://porter.sh/bundle/custom-dockerfile/#porter_mixins
# PORTER_MIXINS

```

</p>
</details>

<details><summary>porter.yaml</summary>
<p>

```yaml
name: porter/reproduce-porter-error
version: 0.0.9
description: "Bundle to deploy our demo apps"
registry: placeholder
dockerfile: Dockerfile.tmpl
schemaVersion: 1.0.0-alpha.1

mixins:
  - exec
  - ansible:
      otherPipDependencies:
        - virtualenv
        - psycopg2
        - openshift
  ## No explicit use of these mixins but we use this config to don't have to know how to install kubectl & helm
  - kubernetes
  - helm3:
      clientVersion: v3.10.0

parameters:
  - name: git-token
    description: Git token to use to clone ArgoCD repository
    type: string
    env: GIT_TOKEN
    sensitive: true

install:
  - exec:
      description: "Description of the command"
      command: echo # The command to run, must be on the PATH
      arguments: # arguments to pass to the command
        - "Hello install !"

upgrade:
  - exec:
      description: "Description of the command"
      command: echo # The command to run, must be on the PATH
      arguments: # arguments to pass to the command
        - "Hello upgrade !"


uninstall:
  - exec:
      description: "Description of the command"
      command: echo # The command to run, must be on the PATH
      arguments: # arguments to pass to the command
        - "Hello uninstall !"
```

</p>
</details>

3. Run this porter command `...`

```bash
porter publish --registry="my_acr.azurecr.io" --force ## Yes I'm using an ACR, may be the error comes from here ?
```

## Expected behavior

The `porter publish` shoud just push my image and never rebuild it.

## Porter Command and Output

1. porter build command (went well)

[porter-build.txt](https://github.com/getporter/porter/files/9731258/porter-build.txt)

2. porter publish (went wrong then push my previously built image)

[porter-publish.txt](https://github.com/getporter/porter/files/9731293/porter-publish.txt)

## Version
Copy the output of `porter version` below

`porter v1.0.0 (89ad7ed6)`

## Other hypothesis

My image is kind of big (2GB+). May be the issue could some kind of caches that takes a long time to update, so the publish tries to rebuild an unfound image (in its cache) then finally found it after some retries ?

## Azure pipelines

I don't think this a workstation issue, because I'm runnning my builds in Azure pipeline in some Microsoft hosted agents (i.e kind of very general VMs and that could be considered clean every time).

For information, here are the relevant steps on my pipeline : 

<details><summary>azure-pipelines.yaml</summary>
<p>

```yaml
stages:
  - stage: snapshot
    displayName: Build snapshot porter app
    pool:
      vmImage: ubuntu-latest
    jobs:
      - job: snapshot
        displayName: Build snapshot porter app
        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: my_acr

          - task: Bash@3
            displayName: Install porter
            inputs:
              targetType: inline
              script: |
                set -e
                curl -L https://cdn.porter.sh/latest/install-linux.sh | bash
                echo "##vso[task.setvariable variable=PATH]${PATH}:~/.porter"

          - task: Bash@3
            displayName: Porter build
            inputs:
              targetType: inline
              script: |
                set -e
                porter mixins install --url https://github.com/LvffY/ansible-mixin/releases/download ansible
                porter mixins install --feed-url https://mchorfa.github.io/porter-helm3/atom.xml helm3
                porter mixins install kubernetes
                porter build --build-arg GIT_TOKEN=$GIT_TOKEN --build-arg BUNDLE_USER=porter
            env:
              GIT_TOKEN: "This is a secret for build time !"

          - task: Bash@3
            displayName: Porter publish
            retryCountOnTaskFailure: 10
            inputs:
              targetType: inline
              script: |
                set -e
                porter publish --registry="my_acr.azurecr.io" --force

```

</p>
</details>
