### ISSUE TITLE
Exec mixin requires called executable to be on the path or specified with a relative path

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2420]
## Describe the bug
When I rebuilt the otel-jaeger example with porter v1.0.1, I noticed that it broke the bundle. Previously the bundle was running the helpers script with `helpers.sh` without a relative path prefix. That worked when it was built with porter v1.0.0-alpha.20. Something we did since then broke calling the script that way, and it now gives an error about helpers.sh not being on the path.

## To Reproduce
1. Checkout the example bundles repository
2. cd to otel-jaeger
3. `porter build && porter install --allow-docker-host-access`

## Expected behavior
The bundle should install successfully but instead it fails.

## Porter Command and Output
```
$ porter install --allow-docker-host-access
TRUNCATED
/cnab/app helpers.sh set-config
2022-10-14T19:43:10.4403953Z         	            	couldn't run command /cnab/app helpers.sh set-config: exec: "helpers.sh": executable file not found in $PATH
2022-10-14T19:43:10.4404821Z         	            	Error: couldn't run command /cnab/app helpers.sh set-config: exec: "helpers.sh": executable file not found in $PATH
2022-10-14T19:43:10.4405295Z         	            	exit status 1
```

## Version
1.0.1

**Comment by schristoff** [comment]
This issue is linked [here too](https://github.com/getporter/examples/pull/23) with recreation steps.
Basically, before the exec mixin could be ran like this:
```
- exec:
      description: "Create OpenTelemetry configuration"
      command: helpers.sh
      arguments:
        - set-config
  - docker-compose:
  ```

But now it needs to be:

```
- exec:
      description: "Create OpenTelemetry configuration"
      command: ./helpers.sh
      arguments:
        - set-config
  - docker-compose:
  ```

or else we get the error pasted above. One thing when we go to support this is that it still works for **all OSes**
