### ISSUE TITLE
Support source mappings for an installation's param overrides

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2446]
Currently, an installation can specify either the names of parameter sets to use, or it can specify user overridden parameters provided on the command-line with the --param PARAM=VALUE flag.

On the display installation that is used as input to `porter installation apply` this is represented as:

```yaml
schemaType: Installation
name: mybuns
parameters:
  log-level: 11
```

On the stored installation this is represented as:

```yaml
schemaType: Installation
name: mybuns
parameters:
  - name: log-level
    source:
      value: 11
```

When porter generates a [workflow resource](https://github.com/getporter/proposals/pull/13), we need to be able to pass more than just hard-coded values to an installation in the workflow, such as outputs from other bundles in the workflow. As outlined in a separate issue (TODO) we also need to be able to pass one off credential set mappings which will need to work the same as parameter sets.

The only way to do that right now with the current display installation schema is to create an independent credential/parameter set and reference it on the installation. But what if we supported specifying _either_ a hard coded value or a mapping on an installation's overridden param/creds?

```yaml
schemaType: Installation
name: mybuns
parameters:
  log-level: 11
  db-conn-str:
    source:
      secret: some-secret
```

We can make this work by defining a custom unmarshal for the parameterset that checks if the parameter is a primitive, in which case use a value source mapping, otherwise if it's a struct, unmarshal it as a normal source strategy.
