### ISSUE TITLE
How to pass a JSON string in through a parameter without porter trying to interpret it into additional parameters

### ISSUE THREAD

**Issue by dlmiller322** [getporter/porter#2461]
**What is your question?**
How would you pass in a parameter to porter install where the value is made up of JSON? Within that JSON file are parameters that need to be passed into the powershell script that is being run in the porter docker image. Basically, we want to be able to take a JSON string in through a parameter intact, so that the install.ps1 script can ingest it as JSON and use it.

We were doing this before with format something like `-overrides '{{ bundle.credentials.overrides }}'`, but something appears to have changed with how porter processes JSON being passed in via a parameter in the latest version.

**What have you tried already?**
Tried putting single quotes around the JSON parameter value (the one in question is -overrides) and without them:
```
install:
  - exec:
      description: "Deploy CFS via script"
      command: pwsh
      arguments:
      - ./porteractions/install.ps1
      - -SqlHostname
      - ${ bundle.parameters.SqlHostname }
      - -overrides
      - '${ bundle.credentials.overrides }'
```

**Where have you looked already to figure this out?**
https://porter.sh/parameters/
https://porter.sh/quickstart/parameters/
https://github.com/getporter/porter/blob/main/pkg/schema/parameter-set.schema.json

**Was the existing documentation unclear or had gaps?**
I am not sure if there is an existing page that answers this, and it's a pretty niche use case, but it might be good to have a page that clearly lists what types of data can be passed in using a porter parameter or parameter set, and how to preserve the value/type of each type of parameter as they are passed into the install.ps1 script.

**Comment by dlmiller322** [comment]
Bump for attention. This issue is keeping us from updating to the latest version of porter, since what we're doing relies on the ability to pass in an unknown number of unknown parameters through porter.yaml into the install.ps1 and related Powershell scripts. If we can't do that, then we can't upgrade porter to the latest version.

Any assistance anyone could provide would be greatly appreciated!

**Comment by carolynvs** [comment]
The problem is how the template variable is expanded. When passing an argument to the exec mixin, sometimes the argument needs to be quoted, and since we are dealing with YAML too, that involves two quotes unforntunately.

```
'"${bundle.parameters.users}"'
```

Here is an example bundle that demonstrates how to keep the quotes around an argument:

```yaml
schemaVersion: 1.0.0
name: json-parameter
version: 0.1.0
description: Escape the json in an argument
registry: "localhost:5000"

mixins:
  - exec

parameters:
  - name: users
    type: string
    env: USERS
    applyTo:
      - install
      - upgrade

install:
  - exec:
      description: "Print Users"
      command: echo
      arguments:
        - '"${bundle.parameters.users}"'

upgrade:
  - exec:
      description: "Print Users"
      command: echo
      arguments:
        - '"${bundle.parameters.users}"'

uninstall:
  - exec:
      description: "Uninstall"
      command: echo
      arguments:
        - bye

```

```
$ porter install json --param 'users=[{"name":"carolyn"}]'

executing upgrade action from json-parameter (installation: quickstart/json)
Print Users
"[{"name":"carolyn"}]"
execution completed successfully!
```

Here is some more information about the double quote escape trick I used: https://getporter.org/best-practices/exec-mixin/#quoting-escaping-bash-and-yaml
