### ISSUE TITLE
Cannot set a parameter to the output of a dependency

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2560]
Porter's v1 of dependencies says that it supports the following:

```
parameters:
- name: connection-string
  type: string
  source:
    dependency: mysql
    output: connstr
```

But this doesn't work in practice, because porter's parameter validation on the bundle returns the folowing error, before even running the dependencies:

```
parameter "connection-string" is required
```

I have verified this behavior was incorrect before #2476 was merged. It's not clear how long this has been broken but we should check v0.38 and v1.0.0. Depending on how long this has been incorrect we can figure out if it's worth fixing with v2 of dependencies coming out "soon".
