### ISSUE TITLE
Specify parameter source with templating?

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2561]
One change in PEP003 is the use of template syntax in areas outside of the install/upgrade/uninstall actions. For example, when specifying a dependency's parameters you can use template syntax to set it

```yaml
dependencies:
  requires:
    - name: mydb
      parameters:
        username: ${bundle.parameters.username}
```

Should we do the same for parameter sources? We could support the older syntax but document/encourage the consistent templating syntax going forward.

```yaml
parameters:
- name: port
  source:
    dependency: mysvc
    output: port

parameters:
- name: port
  source: ${bundle.dependencies.mysvc.outputs.port}
```

ℹ️ Read [PEP003 - Advanced Dependencies](https://github.com/getporter/proposals/blob/main/pep/003-advanced-dependencies.md) for context about how dependencies should work, design details, and notes about desired behavior.
