### ISSUE TITLE
not loading fonts

### ISSUE THREAD

**Issue by Arhell** [getporter/porter#2575]
![Screenshot_1](https://user-images.githubusercontent.com/26163841/218731017-4c59d746-f8c6-498f-aa32-8414365dcd18.png)

**Comment by carolynvs** [comment]
Ooh, yes the site was originally hosted on porter.sh and we have since switched to use getporter.org as our main. Since porter.sh is still used by users (and some parts of our infrastructure), seems like we need to figure out how to configure CORS to support requests from either domain?

**Comment by Arhell** [comment]
I think yes, I will try to solve it, but I'm not sure what will happen

**Comment by carolynvs** [comment]
I'm not sure why the css is retriving the fonts from getporter.org when the site is accessed from porter.sh. The domain isn't specified in the css but maybe that's something to look into fixing instead of CORS.

```scss
# helm-mixins.scss
@font-face {
  font-family: 'CBlack';
  src: url("/fonts/CBlack.otf") format("opentype");
}
```

If you search for netlify cors headers you'll find lots more examples but in general the answer appears to look like this:

```toml
# netlify.toml
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
```
