### ISSUE TITLE
Track references to a dependent installation

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2608]
When we create an installation from a dependency or reuse an installation to satisfy a dependency, we should keep track of who is referencing it and what for. This will allow us to do a few things:

* Know when it's safe to delete an installation, based on if it is still used
* When upgrading an installation, find the associated installations that represent its dependencies and act upon them as a unit or just display the dependencies.

To do this we need to keep these references up to date, both when the relationship is created, and later when the parent installation is updated (perhaps it stops depending on another bundle) or deleted.

Tentatively I think we can store this information on the dependent installation's status:

```yaml
schemaType: Installation
name: mysqldb
status:
  references:
    - installation: myinfra # the name of the installation that is using this one
      dependency: db # the dependency that it satisfies
```

ℹ️ Read [PEP003 - Advanced Dependencies](https://github.com/getporter/proposals/blob/main/pep/003-advanced-dependencies.md) for context about how dependencies should work, design details, and notes about desired behavior.
