### ISSUE TITLE
Relocate dependent bundles during publish

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2669]
During `porter publish`, normally the cnab-to-oci library handles relocating referenced images used by a bundle and updating the relocation mapping files. That library does not understand dependencies however. During publish, either in Porter or a fork of cnab-to-oci, we need to push dependencies when they don't exist, and ensure that the relocation mapping file is updated with their new location.

For example:

```yaml
# porter.yaml
dependencies:
  requires:
    - name: mysql
      bundle:
        reference: example.com/mysql:v1.2.3
```

When the bundle is published to --registry=localhost:5000, the referenced mysql bundle should be copied to localhost:5000/mysql:v1.2.3 (following porter's existing relocation naming conventions).

The dependency in the final porter.yaml should be rewritten to use a digest

```
# porter.yaml
dependencies:
  requires:
    - name: mysql
      bundle:
        reference: example.com/mysql@sha256:abc123
```

Then an entry should be added to relocation-mapping.json

```json
{
  "example.com/mysql@sha256:abc123": "localhost:5000/mysql@sha256:RELOCATED_DIGEST"
}
```
