### ISSUE TITLE
Relocated bundles should also relocate the original tag

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2670]
When we relocate a bundle as part of #2669, we should also copy over the tag instead of only preserving and relocating the digest. This is necessary because porter uses the tag to determine the bundle version

For example,

```yaml
# porter.yaml
dependencies:
  requires:
    - name: mysql
      bundle:
        reference: example.com/mysql:v1.2.3
        version: 1.2.x
```

After that bundle is relocated the porter.yaml looks like this

```yaml
# porter.yaml
dependencies:
  requires:
    - name: mysql
      bundle:
        reference: example.com/mysql@sha256:REPOSTIORY_DIGEST
        version: 1.2.x
```

In order to evaluate the version constraint on the dependency, and allow the user to always select the most recent dependency that satisfies the constraints, we need to also push the tags for that bundle. (out of scope: if they are replicating or copying bundles using other tools such as skopeo it's on them to preserve the tags)

As a test, we should be able to publish two versions of a bundle (one with mysql version v1.2.3 and another with mysql v1.2.4 as a dependency) with a dependency to registry 1, relocate it across an airgap to registry 2. Then you should be able to install the version of the bundle that relies on v1.2.3 of mysql, and when configured to select the highest matching version, it should locate the v1.2.4 version of mysql (even though the default bundle is set to 1.2.3). This demonstrates that when we relocate, porter can still use the tags to find the latest version of a dependency.
