### ISSUE TITLE
Persist interface hash on installation status

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#2687]
When porter is searching for existing installations to reuse to satisfy a dependency, we need a way to quickly filter installations to a subset that implement the desired [installation interface](https://github.com/getporter/proposals/blob/main/pep/003-advanced-dependencies.md#installation-interfaces).

I was thinking that we can persist a hash of the installation interface on the status of the installation (next to where we store the current bundle reference/version).

```yaml
schemaType: Installation
...
status:
  bundleReference: example.com/mybuns:v1.2.3
  bundleVersion: 1.2.3
  bundleDigest: sha256:abc123
  installationInterfaceHash: sha256:def456
```

# Questions
- [ ] We need to finalize exactly what is on the installation interface and it is the same as the bundle interface (i.e. does it include creds/params)

ℹ️ Read [PEP003 - Advanced Dependencies](https://github.com/getporter/proposals/blob/main/pep/003-advanced-dependencies.md) for context about how dependencies should work, design details, and notes about desired behavior.
