### ISSUE TITLE
porter param list doesn't display params

### ISSUE THREAD

**Issue by squillace** [getporter/porter#2785]
## Describe the bug
Porter param list doesn't display params that porter param show <name> does display

## To Reproduce
1. Run `porter create` to create hello-porter bundle
2. Edit the porter.yaml to uncomment the mysql parameters and build bundle
3. Run this porter command `porter param generate` to create porter parameter set from the bundle
4. Run this porter command `porter param list` to show created params......

## Expected behavior
A list of one that includes the param set you just generated.

## Porter Command and Output
```
squillace@idiopath:~/work/squillace/howdy$ porter param show mysql
Name: mysql
Created: 1 hour ago
Modified: 1 minute ago

-----------------------------------------
  Name        Local Source  Source Type
-----------------------------------------
  mysql_user  RALPH         env
squillace@idiopath:~/work/squillace/howdy$ porter param list
-----------------------------
  NAMESPACE  NAME  MODIFIED
-----------------------------
squillace@idiopath:~/work/squillace/howdy$
```

## Version
Copy the output of `porter version` below

porter v1.0.14 (0e739d88)

**Comment by alekseybb197** [comment]
Done
https://github.com/getporter/porter/pull/2788

**Comment by troy0820** [comment]
@schristoff does the above PR close this issue?

**Comment by troy0820** [comment]
This seems to work with v0.1.14 for the following outputs:
`json, yaml` where you see the following output:
```json
[
  {
    "schemaType": "ParameterSet",
    "schemaVersion": "1.0.1",
    "namespace": "",
    "name": "porter-hello",
    "parameters": [
      {
        "name": "mysql_user",
        "source": {
          "env": "fake-user"
        }
      }
    ],
    "status": {
      "created": "2023-07-10T09:31:51.86352484-04:00",
      "modified": "2023-07-10T09:31:51.86352484-04:00"
    }
  }
]
```
```yaml
- schemaType: ParameterSet
  schemaVersion: 1.0.1
  namespace: ""
  name: porter-hello
  parameters:
    - name: mysql_user
      source:
        env: fake-user
  status:
    created: 2023-07-10T09:31:51.86352484-04:00
    modified: 2023-07-10T09:31:51.86352484-04:00
```
Plain text doesn't show the values but just the name of the bundle 
```
---------------------------------------
  NAMESPACE  NAME          MODIFIED
---------------------------------------
             porter-hello  2023-07-10
```
Is that what we want? 
Or are we looking at doing this: 

```
------------------------------------
  NAME        VALUE     MODIFIED
------------------------------------
  mysql_user  fake-user 2023-07-10

```
