### ISSUE TITLE
Specifying multiple dependencies with the same name doesn't produce an error or warning

### ISSUE THREAD

**Issue by kichristensen** [getporter/porter#3067]
## Describe the bug
Specifying multiple dependencies with the same name, does not produce an error or warning. The resulting bundle will only install the last dependency with the name, and outputs will only be taken from the last dependency.

## To Reproduce
1. Run `porter create`
2. And two dependencies with the same name, e.g., 
   ```yaml
   dependencies:
     requires:
       - name: hello
         bundle:
           reference: ghcr.io/getporter/porter-hello:v0.2.0
         parameters:
           name: First
       - name: hello
          bundle:
            reference: ghcr.io/getporter/porter-hello:v0.2.0
          parameters:
            name: Second
   ```
3. Run this porter command `porter install`
4. Notice that the dependency is only installed once and that there are no errors no warnings

## Expected behavior
An error that a dependency with the same name is specified multiple times, or at least a warning.

## Porter Command and Output
```
$ porter install
Executing dependency hello...
executing install action from porter-hello (installation: /porter-hello-hello)
No existing bundle state to unpack
Install Hello World
Hello, Second
Collecting bundle outputs...
  - name
Packing bundle state...
execution completed successfully!
executing install action from porter-hello (installation: /porter-hello)
Install Hello World
Hello World, Second
execution completed successfully!
```

## Version
porter v1.0.17 (605e399)
