### ISSUE TITLE
Porter's Template Language

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#316]
# Problem Background

Let's say a step generates an output file, and the next step wants to use it how would that look?

The next step needs to say, "I want to use this output as a file"

```yaml
install:
  - aks:
      outputs:
      - name: kubeconfig
  - helm:
      kubeconfig: "{{ path bundle.outputs.kubeconfig }}"
```

One problem that I found is that we are using mustache and that doesn't support helper functions, so we would need to move to handlebars. Not a huge deal.

But as I thought about this further, I realized that we have a problem representing int and bool types right now. The problem with int/bool is a problem with json,toml and hcl too, not just yaml. **Any templating on top of markup languages where we need to read the markup before parsing the template is** a minefield. Yaml is the least problematic because it doesn't require strings to be quoted.

Consider the following:

 ```
 port: "{{ bundle.outputs.port }}"
 ```

We had to have those quotes in order to load and use the manifest. Unfortunately, there is no way for the templating engine to get rid of the wrapping quotes, and no way for porter to either without awkward hacks. So when a mixin reads in and validates `port`, it is going to fail because its schema required an int (or bool) not a string.

# Porter's Own Template Language

As we found above, mustache (the template engine we use currently) doesn't allow for helper functions, so all my plans include moving to handlebars. Handlebars is a superset of mustache that supports helper functions. This will allow users to transform outputs which is going to be critical for porter.

NOTE: Since we plan to use handlebars under the hood there is nothing stopping someone from quoting properly and using handlebars up the wazoo. What I am proposing here is just nicer syntax which that also fixes the problems outlined above with int and bool.

## Option 1: Ugly Handlebars
```yaml
install:
  - aks:
      outputs:
      - name: kubeconfig
  - helm:
      kubeconfig: <% path bundle.outputs.kubeconfig %>
      set:
        kubeport: <% bundle.outputs.kubeport %>
        db: "<% bundle.params.dbhost %>:<% bundle.outputs.dbport %>"
```

1. Replace `<% %>` with `{{ }}`
1. Run handlebars

Pros:
* Let's people use their existing knowledge/docs of handlebars
* Workaround the problem with requiring surrounding quotes for {{ }}

Cons:
* Not so easy on the eyes, verbose

## Option 2: Transparent Handlebars

```yaml
install:
  - aks:
      outputs:
      - name: kubeconfig
  - helm:
      kubeconfig: bundle.outputs.kubeconfig
      set:
        kubeport: bundle.outputs.kubeport
        db: "bundle.params.dbhost:bundle.outputs.dbport"
```

This relies on the fact that all of our templated values start with `bundle.` and this gives us the ability to find them without needing the handlebar delimiters.

1. Find `bundle.*` words and wrap it with `{{ bundle.* }}`
1. Run handlebars

Pros:
* Reads pretty nice since we got rid of the deliminator in most cases

Cons:
* Need to fallback to using `<% %>` deliminators when concatenating with letters in a int/bool field which I can't even come up with a valid scenario for.

## Recommendation

We should do both and recommend transparent handlebars, using it for all of our documentation. We have ugly handlebars available to fall back to as a break glass option
but we can't see it being needed. It will be documented as a "in case you get stuck, you can do this".

### Function Syntax
Helper functions can have multiple arguments. We want something that can be easily
regexed and put back into the form `FUNC ARG1 ARG2 ARGN`. It needs to work well
with intellisense.

```
porter.FUNC(arg1, arg2... argN)
```

1. Find porter.FUNC(*)
2. Replace with FUNC *

Pros:
* Having the `porter.*` helps intellisense know when to show a list of functions
* Symmetrical to `bundle*`

Cons:
* A bit verbose

**Comment by jeremyrickard** [comment]
For complicated scenarios where we want to do concatenation, I think I might like option 1 better.

>  db: "<% bundle.params.dbhost %>:<% bundle.outputs.dbport %>"

vs

> db: "bundle.params.dbhost:bundle.outputs.dbport"

The verboseness of the `<% %>` delimiters make it easy to visually scan through and see. I like transparent handlebars lack of the delimiters though, i think it's closer to what we had landed on originally for the `source: x.y.z` usage. I think I'd probably end up using the delimiters for the concatenation/interpolation scenarios and might use that for consistency.

**Comment by itowlson** [comment]
The transparent option is attractive but feels like it might be _too much_ magic.  It's hard to visually distinguish strings that are literal from strings that are going to be replaced, especially in interpolation situations as Jeremy pointed out.

Also from an intellisense point of view the user has to type a lot more before we can trigger completions (we can trigger on `bundle.` but not on `<%`.

Re function syntax,

You probably need the delimiters if you want to support the sort of function calls you mentioned in email e.g. `trunc bundle.outputs.foo 10` - otherwise there's really no way to know what is meant as interpolated code and what as literals.  The `porter.` prefix feels a bit unnatural - the whole thing is Porter, why do I need to identify functions in particular as Porter-ish?  An interpolation/delimiter syntax feels like it might work better here.  Or a punctuation notation such as `@trunc` or something.

Some other options to consider (though I suspect these have already been discussed):

* Environment variable style syntax e.g. `$bundle.params.host` or `$(bundle.params.host)`
* JS or C# interpolated string syntax e.g. `[backtick]${bundle.params.host}[backtick]` or `[backtick]{bundle.params.host}[backtick]` (where the backtick turns on interpolation a la JS and the $ or { indicates that this is an expression to interpolate; sorry haven't figured out how to escape backticks) or `$"{bundle.params.host}"` (where the `$"` turns on interpolation)

**Comment by carolynvs** [comment]
for v1 I'd like only a way to address the ability to use a number/bool (not string) as a field value in a template. I need to write up a proposal, but essentially we can use a yaml node tag to identify templated nodes.

**Comment by carolynvs** [comment]
I am prototyping out the proposed solution of changing the template deliminators to `${ ... }`.  Right now because we use the default mustache handlebars `{{ ... }}`, they must be escaped because curly braces have special meaning in YAML. By switching to a deliminator that starts with a text character, we wouldn't need the quotes anymore and would avoid the type problems in the OP.

Here's an example of what a porter.yaml would look like
```yaml
install:
- docker:
    description: "Run an image"
    run:
      image: getporter/whalesayd:${ bundle.parameters.tag } # pass a string
      name: whalesay
      detach: true
      ports:
        - host: ${ bundle.parameters.port } # pass a number
          container: 8080
      suppress-output: ${ bundle.parameters.silent } # pass a boolean
```

I realize this would be a big breaking change (which is why this is slated for 1.0), and would welcome suggestions for how to help bundle authors migrate over. I think we could coordinate this feature with #1566 (including the schema version for the porter.yaml file as a field), so that older schemas would be parsed with the original {{ }} templating and newer schemas would use ${ }.
