### ISSUE TITLE
Suggestion: Mixins that manage their own CNAB lifecycle

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#318]
Some mixins are in a position to completely manage the cnab lifecycle. A good example is helm. Given the release name, chart and a values file, the helm mixin has enough information to handle all of the CNAB actions without the user explicitly declaring them in the manifest and saying what to do for each one.

Porter could allow these mixins to have metadata defined outside of a cnab action, and then call them for every cnab action executed on the bundle. The mixin could then decide what action if any is appropriate to take. Some mixins like exec, obviously couldn't support this, but others are a great fit.

```
name: mybundle

mixins:
- name: helm
   version: v0.8.x

helm:
  name: wordpress
  chart: stable/wordpress
  namespace: default
  values: values.yaml
```

Porter would determine when to execute the mixin based on any dependencies on the mixins outputs, and its dependencies on outputs as well.
