### ISSUE TITLE
Wiring Images in Airgapped Bundle

### ISSUE THREAD

**Issue by jmcudd** [getporter/porter#3237]
I believe this example of how to wire images in an airgapped environment is incorrect.

https://github.com/getporter/porter/blob/8dbb923f3ee704dfb1d9c48b9b9616436c31d4f5/docs/content/docs/references/examples/airgap.md?plain=1#L78 
This is referencing the source repository and does not reference the bundled image.

To fetch a bundled image dependency the repository has to be the bundle repository plus the image digest.

For example let's say we had a bundle called `my-bundle`, with a mongo image referenced in it.

```yaml
name: my-bundle
repository: registry.mylab.internal:5000
...
images:
  mongo:
    description: Database for storing documents.
    imageType: docker
    repository: docker.io/mongodb/mongodb-community-server
    digest: sha256:674b3dc4eb246760faeea49394f5d446a6ec1082f3f9992514fa9935f55cc042
```

If my bundle is published to `registry.mylab.internal:5000/my-bundle`, the mongo image is actually located here:

```
registry.mylab.internal:5000/my-bundle@sha256:674b3dc4eb246760faeea49394f5d446a6ec1082f3f9992514fa9935f55cc042
``` 

But the `${bundle.images.mongo.repository}` is equal to:

```
docker.io/mongodb/mongodb-community-server
```

This is not accessible in an airgapped environment.
