### ISSUE TITLE
Object parameters cannot be read from a file

### ISSUE THREAD

**Issue by lbergnehr** [getporter/porter#3257]
## Describe the bug
According to
https://github.com/getporter/porter/blob/f61648fcb851ab4bf6d062b593b3d5ccd6e91bdb/docs/content/docs/bundle/manifest/_index.md?plain=1#L182,
an object parameter should, much like the `file` type parameter, be able to be
taken from a file directly when specified using the `--param` option in e.g.
`porter install`.

## To Reproduce
1. Use this porter.yaml:

   ```yaml
   schemaType: Bundle
   schemaVersion: 1.0.1
   name: porter-repro
   version: 0.1.0
   description: "An example Porter configuration"
   registry: "localhost:5000"

   # Declare and optionally configure the mixins used by the bundle
   mixins:
     - exec

   parameters:
     - name: object_parameter
       type: object
       path: /cnab/app/object_parameter.json

   # Define the steps that should execute when the bundle is installed
   install:
     - exec:
         description: "Install Hello World"
         command: echo
         arguments:
           - install ${ bundle.parameters.object_parameter }

   # Define the steps that should execute when the bundle is upgraded
   upgrade:
     - exec:
         description: "World 2.0"
         command: ./helpers.sh
         arguments:
           - upgrade

   # Define the steps that should execute when the bundle is uninstalled
   uninstall:
     - exec:
         description: "Uninstall Hello World"
         command: ./helpers.sh
         arguments:
           - uninstall
   ```

1. Put the following in `object_parameter.json`:

   ```json
   {
     "key": "value"
   }
   ```
1. Run `porter install --param object_parameter=./object_parameter.json`
1. Observe the error:

   ```
   unable to convert parameter's object_parameter value ./object_parameter.json to the destination parameter type object: could not unmarshal value ./object_parameter.json into a json object: invalid character '.' looking for beginning of value
   ```

## Expected behavior
The file should be read and marshalled into the object parameter
representation if the parameter given in the `--param` option is pointing to a
file.

## Version

```
porter v1.2.0 (45c17c15)
```
