### ISSUE TITLE
`porter installation output show` should not print newline after the output value

### ISSUE THREAD

**Issue by lbergnehr** [getporter/porter#3274]
## Describe the bug
When running `porter installation output show ...` the output value is appended with a newline. This effectively alters the value of the output if directly using it, e.g. in a shell pipe and might require additional trimming in order to work as intended.

## To Reproduce
1. Use the following `porter.yaml` and create an installation:
```yaml
schemaType: Bundle
schemaVersion: 1.0.1
name: porterrepro
version: 0.1.0
description: "An example Porter configuration"
registry: "localhost:5000"
mixins:
  - exec

outputs:
  - name: greeting
    type: string

install:
  - exec:
      description: "Install Hello World"
      command: echo
      arguments:
        - -n
        - hello world
      outputs:
        - name: greeting
          regex: "(.*)"
upgrade:
  - exec:
      description: "World 2.0"
uninstall:
  - exec:
      description: "Uninstall Hello World"
```
2. Run `porter installation output -i porterrepro show greeting | cat -E`
3. This will display a `$` at the end, indicating a newline as part of the output (something we explicitly didn't add, using `echo -n`).

## Expected behavior
It should not display the `$` at the end, indicating no newline added.

## Version
porter v1.2.0-10-g48de62ea (48de62ea)
