### ISSUE TITLE
hoover mixin

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#352]
I want a mixin that can listen for all the outputs being created by the bundle and "hoover them up". For example, the mixin could listen for all the outputs and then store them in a key value store.

```yaml
mixins:
- azurehoover:
  collector: true
  destination: "{{ bundle.parameters.hoover-bucket }}"

# or use a global config entry here
# azurehoover:

install:
- helm:
    outputs:
    - name: password
       collect: false
    - name: host
      # by default everything is collected
```
