### ISSUE TITLE
poor error message: more than one mixin specified

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#370]
When the yaml for an action step is malformed, and more than one key is at the root of the step, you trigger "more than one mixin specified". But the error message isn't clear on what is wrong and how to fix it.

Let's help people out by:
* Improving the error message
* Adding the error message to the FAQ and explain how to fix

# Reproduction Steps
1. make a new directory and inside it run porter create
2. Edit porter.yaml and mess up the indentation of the install step (note that description and the other fields should be indented underneath exec)
    ```yaml
    install:
        - exec:
          description: "Install Hello World"
          command: ./helpers.sh
          arguments:
            - install
    ```
3. Run porter build

```console
$  porter build
Using buildkit build driver
1 error occurred:
	* validation of action "install" failed: more than one mixin specified
```

Ideally the error message should say that the first step in the install action is malformed and they should check that all of the mixins's child fields are indented underneath the name of the mixin.
