### ISSUE TITLE
Suggested naming convention for image/bundles

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#459]
Porter should document suggested naming conventions for the invocation image and the bundle. I think it would help to have people use similar names and save people time wondering about it themselves. Then based on the convention we can default it for them (See #383).

My recommendation is that we optimize for the most natural / short naming of the tag, since that is what they are typing in their commands. They aren't typing in the invocation image, so that's where the longer qualifier should go.  I think of the invocation image as the "installer" but suggestions welcome!

```yaml
registry: {{bundle.build.env.user}} # See https://github.com/deislabs/porter/issues/319
tag: {{bundle.registry}}/{{bundle.name}}:{{bundle.version}}
invocationImage: {{bundle.registry}}/{{bundle.name}}-installer:{{bundle.version}} # We can default this if not present
```

The `porter create` command should be generating these templated defaults. Ideally `invocationImage` is not in the template at all, and we generate it based on the bundle's tag entirely using our naming convention and push it to the same registry.
