### ISSUE TITLE
Help generating random strings

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#491]
Sometimes I need to generate random strings. For example I'm making a workshop and everyone is going to run into a global naming constraint. It would be nice if I could use porter's templating to generate a rando string to make my life easier.

```yaml
install:
  - aws:
      description: "Create Bucket"
      service: s3api
      operation: create-bucket
      flags:
        bucket: "{{ bundle.parameters.bucket }}-{{ porter.randomName(6) }}"
        region: "{{ bundle.parameters.region }}"
```
