### ISSUE TITLE
exec mixin should allow certain commands to have non-zero exit codes

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#592]
Sometimes a command is allowed to have a non-zero exit code. For example when deleting a resource that is already gone, our mixins check for the "not found" text on stdout and then continue gracefully.

* Mixin authors should be able to define in the delete action text that means that the resource was already deleted, so that the action succeeds.
* Bundle authors should be able to define text for mixins extending exec (and for exec itself) where if that text is in stdout/err, then the exit code can be ignored and the command considered successful.

**Ignore a non-zero exit code when stderr/stdout contains a message**
```yaml
- exec:
    command: helm
    arguments:
    - delete
    - myRelease
    ignoreError:
      output:
        contains: ["not found", "not exist"]
```

**Ignore a non-zero exit code when stderr/stdout matches a regular expression**
```yaml
- exec:
    command: helm
    arguments:
    - delete
    - myRelease
    ignoreError:
      output:
        regex: ["release: .* not found"]
```

**Ignore some exit codes**
```yaml
- exec:
    command: helm
    arguments:
    - delete
    - myrelease
    ignoreError:
      exitCodes: [1, 127]
```

**Ignore all non-zero exit codes**
```yaml
- exec:
    command: rm
    arguments:
    - foo
    ignoreError:
      all: true
```

If we make the change to the our mixin framework directly (which a lot of mixins use), then other mixins besides the exec mixin can update and get this feature for free too

https://github.com/getporter/porter/blob/5efddb87b292184baceaf64a3301639e3949e4d1/pkg/exec/builder/execute.go#L145-L148

This should include test cases for gracefully handling errors, either in execute_test.go or in the exec mixins tests, whichever is easier to add a new test for. I don't believe we have an existing test that you can modify.

It's totally fine to just implement a single use case listed here. The best one to start with is ignoring all errors (last use case).
