### ISSUE TITLE
Consider: uninstall in cases where porter claim deletion prevents any ops on remaining resources

### ISSUE THREAD

**Issue by squillace** [getporter/porter#756]
helm chart that installs CRDs; uninstall does NOT remove CRDS by default. 

If the delete action removes the helm chart, then it also removes the porter instance from the claims folder. NOW, however, I cannot have a porter custom action to delete the CRDs _because the porter instance has been removed_. 

so, to encapsulate chart and crd removal independently, I have to no-op the uninstall verb and then have separate custom actions for each type.

Do I understand this correctly?

**Comment by vdice** [comment]
I don't think custom actions are necessarily required to accomplish this.

One way could be, instead of the `helm` mixin step being the only one (or last) step under the `uninstall` action:
```
uninstall:
  - helm:
      description: "Uninstall Helm release containing CRDs"
      releases:
        - myrelease
```
we could add the additional mixin step for cleaning up the CRDs (probably using the exec mixin assuming the invocation image has kubectl?):
```
uninstall:
  - helm:
      description: "Uninstall Helm release containing CRDs"
      releases:
        - myrelease
  - exec:
      description: "CRD cleanup"
      command: kubectl
      arguments:
        - delete
        - mycrd
      flags:
        n: mynamespace
```
