### ISSUE TITLE
Helm/Porter issue: modifying charts in order to achieve copy/archive support defeats drop-in artifact goals

### ISSUE THREAD

**Issue by squillace** [getporter/porter#759]
Hey all. 

I am creating a bundle that can deploy porter online but be copyable and moveable. But we currently see to have to modify the helm chart to use digests rather than tags. I would think that, at build time, we could pull the tags to resolve to digests, but that's not what we do. (I'm sure for a good reason.)

If modifying the chart to support digests is required to move a chart offline -- in this case, it requires me to modify the official rudr chart merely to create a bundle and/or push that modification into a tree that I don't own and maybe doesn't want to do it that way. (Although I also guess that's a great scenario for relocation as well.)

On the one hand, copying and offline support are niche environments. On the other, too many hurdles restrict usage, which restricts its value to the world as well. What do we think here?

**Comment by jeremyrickard** [comment]
Hey @squillace I did a little digging/experimenting. 

This isn't really an issue specific to _Helm_. It's really an artifact of how CNAB (the spec) and cnab-to-oci are handling the images. Since CNAB is in the business of immutability, it's dealing with digests. Let's consider the following `porter.yaml` context:

```yaml
name: spring-music
version: 0.6.0
description: "Run the Spring Music Service on Kubernetes and Digital Ocean PostgreSQL"
invocationImage: jeremyrickard/porter-do:v0.6.0
tag: jeremyrickard/porter-do-bundle:v0.6.0

images:
  spring-music:
      description: "Spring Music Example"
      imageType: "docker"
      repository: "jeremyrickard/spring-music"
      tag: "v1.0.0"
      #digest: "sha256:8f1133d81f1b078c865cdb11d17d1ff15f55c449d3eecca50190eed0f5e5e26f"
```

This ends up giving us the following relocation mapping:


```
"jeremyrickard/porter-do:v0.6.0":"jeremyrickard/porter-do-bundle@sha256:da879273203b36b60b10590a66b791f5484e5353486de74e3cd2f6d1cf2ff7f5","jeremyrickard/spring-music:v1.0.0":"jeremyrickard/porter-do-bundle@sha256:8f1133d81f1b078c865cdb11d17d1ff15f55c449d3eecca50190eed0f5e5e26f"}
```

So if we are specifying the non-digested form, we still get the digested form in the relocation mapping. `cnab-to-oci` relocates these images _by default_, so it will always get moved. This isn't really a HELM thing as I mentioned, it's a "cnab bundles relocate stuff and deal in immutable references" thing. The best practice is to copy the chart into your bundle source anyway...not rely on one on the interwebs. Is modifying it after you've copied it into the bundle that much worse?
