### ISSUE TITLE
Provide parameters interactively [Feature Request]

### ISSUE THREAD

**Issue by cocowalla** [getporter/porter#793]
# Problem
Some apps have a lot of configurable parameters, which can be fiddly to supply using the `porter install --param/param-file` syntax. Additionally, having to supply several parameters on the command line can be a bit daunting for some users who are less Linux-savvy.

# Request
In addition to the existing `--param/param-file` syntax, this request is for the possibility to supply parameter values interactively.

There would need to be a means of entering interactive mode, such as:

`porter install --interactive` or in short form `porter install -i`

Ideally this could be combined with the existing `--param/param-file` syntax, which would provide default values that could be changed interactively if required (or perhaps suppress those prompts).

# Worked Example
Consider the following porter YAML snippet:
```yaml
parameters:
- name: database_name
  type: string
  description: Name of the database to create
  default: widgets
  
- name: database_port
  type: integer
  description: TCP port the database server will listen on
  default: 5432
```
The following command is issued:

```bash
porter install MyApp --interactive --param database_name=myergen
```

The interactive prompts begin:

```bash
Please provide parameter values

Name of the database to create
database_name: myergen
```
Here the value is defaulted from the value provided on the command line, and can be adjusted if required.

```bash
TCP port the database server will listen on
database_port: 5432
```
Here the value is defaulted from the YAML config, and can be adjusted if required.
