### ISSUE TITLE
Request: Support passing dependency outputs as parameters to sibling dependency

### ISSUE THREAD

**Issue by MikeLarah** [getporter/porter#818]
# Feature request

It'd be great if the following scenario was supported:
- Parent bundle has 2 child dependencies
- Child bundle 1 has outputs
- Able to pass output from child bundle 1 as a parameters to sibling child bundle 2

e.g.

```
dependencies:
  dependency-child-1:
    tag: ***.azurecr.io/porter/dependency-child-1/bundle:0.1.0
  dependency-child-2:
    tag: ***.azurecr.io/porter/dependency-child-2/bundle:0.1.0
    parameters:
      child_2_param: "{{ bundle.dependencies.dependency-child-1.outputs.child_1_output }}"
```

This would help to enable better composability and reuse of bundles.
