### ISSUE TITLE
Injecting colon/hashtag through params can cause invalid yaml

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#851]
## Describe the bug
When we render a step's template from the manifest yaml, we lose the wrapping quotes, which can cause errors such as `mapping values are not allowed in this context` when the value contained has a colon followed by a space.

This is caused by how we use the unmarshaled yaml, instead of the raw yaml from the porter.yaml file. It would be really great if when we need to render a step template, we can identify the proper step stanza from the manifest and not use the unmarshaled yaml. That way we can completely preserve the original text that they used and not lose anything in a yaml round trip.

**Comment by carolynvs** [comment]
Oops a stray comment closed this issue. 😬

**Comment by carolynvs** [comment]
For example after a few tries you finally figure out how to escape your bash foo + yaml like this in the porter.yaml

```yaml
install:
 ….
    c: `echo "{{ bundle.parameters.farts }}"`
```

But because we load that into memory that put it through the yaml.marshal/unmarshal loop we lose the wrapping quotes and it becomes this

```yaml
install:
 ….
    c: echo "{{ bundle.parameters.farts }}"
```

which because parameters has a ` :` in it or a `# ` can trigger the yaml parsing error in the OP.

**Comment by carolynvs** [comment]
Now that we are using go-yaml v3, we can pull out the node and provide the raw yaml to the step, without the round trip through a go struct.

**Comment by VinozzZ** [comment]
I was not able to reproduce the issue with `porter v1.0.0-alpha.22-5-gf6ab3d1d (f6ab3d1d)`. The bundle is correctly rendered and executed with `--no-lint` flag set to true. 
Here's my test setup:
```yaml
# porter.yaml

schemaVersion: 1.0.0-alpha.1
name: examples/porter-hello
version: 0.2.0
description: "An example Porter configuration"
registry: ghcr.io/vinozzz

parameters:
  - name: name
    type: string
    default: porter
    value: test

mixins:
  - exec

install:
  - exec:
      description: "Install Hello World"
      command: bash
      flags:
        c: 'echo "{{ bundle.parameters.name }}"'
...
```

```
$ porter build

install: 1st step in the exec mixin (Install Hello World)
See https://porter.sh/best-practices/exec-mixin/#use-scripts for more information
---
error(exec-101) - bash -c argument missing wrapping quotes
install: 1st step in the exec mixin (Install Hello World)
The bash -c flag argument must be wrapped in quotes, for example
exec:
  description: Say Hello
  command: bash
  flags:
    c: '"echo Hello World"'

See https://porter.sh/best-practices/exec-mixin/#quoting-escaping-bash-and-yaml for more information
---

Lint errors were detected. Rerun with --no-lint ignore the errors.

$ porter build --no-lint

# successfully built
```

``` 
$ porter install -r repo-to-the-bundle --debug
...
=== Step Template ===
exec:
  command: bash
  description: Install Hello World
  flags:
    c: echo "{{ bundle.parameters.name }}"

=== Rendered Step ===
exec:
  command: bash
  description: Install Hello World
  flags:
    c: echo "porter"

...

```
