### ISSUE TITLE
Don't require credentials when applyTo makes them unnecessary

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#877]
For this porter.yaml, it would be really useful if credentials had applyTo, just like parameters and outputs. Then I could define my credentials as only needed for install:

```yaml
credentials:
- name: db-password
  env: DB_PASSWORD
  type: string
  applyTo:
  - install
```

Then porter could inspec the credentials when deciding if they are required and take `applyTo` and the current action into account when enforcing if credentials are required and if the specified credential set satisfies them.

This would require changes to the cnab-spec and cnab-go before we could implement it in porter.
