### ISSUE TITLE
Inject parameters and credentials into dependencies

### ISSUE THREAD

**Issue by carolynvs** [getporter/porter#990]
Ideally I'd love to be able to compose bundles together, by doing something like:

```yaml
name: wordpress-on-aks
version: 0.1.0
description: "Deploys AKS cluster with nginx ingress controller and installs Wordpress"
tag: wordpress-on-aks:0.1.0

parameters:
  - name: aks_cluster_name
    type: string
  - name: dns_name
    type: string
  - name: wordpress_username
    type: string

dependencies:
  aks:
    tag: aks:0.1.0
    parameters:
      cluster_name: "{{ bundle.parameters.aks_cluster_name }}"
  aks-nginx-ingress:
    tag: aks-nginx-ingress:0.1.0
    credentials:
      kubeconfig: "{{ bundle.dependencies.aks.outputs.kubeconfig }}"
    parameters:
      dns_name: "{{ bundle.parameters.dns_name }}"
  wordpress:
    tag: wordpress:0.1.0
    credentials:
      kubeconfig: "{{ bundle.dependencies.aks.outputs.kubeconfig }}"
    parameters:
      username: "{{ bundle.parameters.wordpress_username }}"
      host: "{{ bundle.dependencies.aks-nginx-ingress.outputs.fqdn }}"
```

i.e. being able to pass parameters/credentials/outputs from parent to child, and from sibling to sibling.

This was originally requested by @MikeLarah in https://github.com/Azure/azure-cnab-quickstarts/issues/65#issuecomment-614096619

**Comment by carolynvs** [comment]
Heads up that `bundle.dependencies.aks.outputs.kubeconfig` depends upon #1069

**Comment by marrobi** [comment]
Is this any nearer being completed?

I need to use the parent bundle parameters in the dependency.

Something like:

```
dependencies:
  - name: tre-workspace-vanilla
    reference: xxx.azurecr.io/tre-workspace-vanilla:v0.1.0
    parameters:
      tre_id: "{{ bundle.parameters.tre_id }}"
      workspace_id: "{{ bundle.parameters.workspace_id }}"
      azure_location: "{{ bundle.parameters.azure_location }}"
      address_space: "{{ bundle.parameters.address_space }}"
```
